REM  --------------------------------------------------------------------  1ASY
REM                                                                        1ASY
REM  STRIDE: Knowledge-based secondary structure assignment                1ASY
REM  Please cite: D.Frishman & P.Argos, Proteins XX, XXX-XXX, 1995         1ASY
REM                                                                        1ASY
REM  Residue accessible surface area calculation                           1ASY
REM  Please cite: F.Eisenhaber & P.Argos, J.Comp.Chem. 14, 1272-1280, 1993 1ASY
REM               F.Eisenhaber et al., J.Comp.Chem., 1994, submitted       1ASY
REM                                                                        1ASY
REM  ------------------------ General information -----------------------  1ASY
REM                                                                        1ASY
HDR  COMPLEX (AMINOACYL-TRNA SYNTHASE/TRNA)  19-JAN-95   1ASY              1ASY
CMP  MOL_ID: 1;                                                            1ASY
CMP   MOLECULE: T-RNA (75-MER);                                            1ASY
CMP   CHAIN: R, S;                                                         1ASY
CMP   EC: 6.1.1.12;                                                        1ASY
CMP   ENGINEERED: YES;                                                     1ASY
CMP   MOL_ID: 2;                                                           1ASY
CMP   MOLECULE: ASPARTYL-TRNA SYNTHETASE;                                  1ASY
CMP   CHAIN: A, B;                                                         1ASY
CMP   ENGINEERED: YES                                                      1ASY
SRC  MOL_ID: 1;                                                            1ASY
SRC   SYNTHETIC: YES;                                                      1ASY
SRC   MOL_ID: 2;                                                           1ASY
SRC   ORGANISM_SCIENTIFIC: SACCHAROMYCES CEREVISIAE                        1ASY
AUT  M.RUFF,J.CAVARELLI,B.REES,S.KRISHNASWAMY,J.C.THIERRY,D.MORAS          1ASY
REM                                                                        1ASY
REM  -------------------- Secondary structure summary -------------------  1ASY
REM                                                                        1ASY
CHN  /home/proj/stride/tmp/tmpcaWpibpdb A                                  1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  1    EDTAKDNYGKLPLIQSRDSDRTGQKRVKFVDLDEAKDSDKEVLFRARVHN   50          1ASY
STR        TTTTTTEEE      TTTTT       GGG TTTTTTTb  EEEEEEEE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  51   TRQQGATLAFLTLRQQASLIQGLVKANKEGTISKNMVKWAGSLNLESIVL  100          1ASY
STR       EEEEETTEEEEEEETTTTEEEEEEE BTTTTBTHHHHHHHH  TTTEEEE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  101  VRGIVKKVDEPIKSATVQNLEIHITKIYTISETPEALPILLEDASRSEAE  150          1ASY
STR       EEEEEEETTTTTTTTTTTTEEEEEEEEEEEBT TTTTTTTHHHHH  HHH               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  151  AEAAGLPVVNLDTRLDYRVIDLRTVTNQAIFRIQAGVCELFREYLATKKF  200          1ASY
STR       HHH       HHHHHH HHHHH   HHHHHHHHHHHHHHHHHHHHHHH                 1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  201  TEVHTPKLLGAPSEGGSSVFEVTYFKGKAYLAQSPQFNKQQLIVADFERV  250          1ASY
STR       EE   TTEE  TTTTTTTTEEEEBTTB  EETTTTHHHHHHHHHH TTEE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  251  YEIGPVFRAENSNTHRHMTEFTGLDMEMAFEEHYHEVLDTLSELFVFIFS  300          1ASY
STR       EEEEEEE      TTTTTTEEEEEEEEEETTTTHHHHHHHHHHHHHHHHH               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  301  ELPKRFAHEIELVRKQYPVEEFKLPKDGKMVRLTYKEGIEMLRAAGKEIG  350          1ASY
STR       HHHHHHHHHHHHHHTTTT      TTTT  EEEEHHHHHHHHHHH    T               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  351  DFEDLSTENEKFLGKLVRDKYDTDFYILDKFPLEIRPFYTMPDPANPKYS  400          1ASY
STR       TTT   HHHHHHHHHHHHHHH   EEEEE  BTTTTTTTB BTTTTTTBB               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  401  NSYDFFMRGEEILSGAQRIHDHALLQERMKAHGLSPEDPGLKDYCDGFSY  450          1ASY
STR        EEEEEETTEEEEEEEEE   HHHHHHHHHHH  TTTTHHHHHHHHHHHH               1ASY
REM                                                                        1ASY
REM                .         .         .         .                         1ASY
SEQ  451  GCPPHAGGGIGLERVVMFYLDLKNIRRASLFPRDPKRLRP            490          1ASY
STR           EEEEEEEHHHHHHHHH TTTGGGGTTTT TTTT                            1ASY
REM                                                                        1ASY
CHN  /home/proj/stride/tmp/tmpcaWpibpdb B                                  1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  1    EDTAKDNYGKLPLIQSRDSDRTGQKRVKFVDLDEAKDSDKEVLFRARVHN   50          1ASY
STR        TTTTTTEEE  TTT  GGG        GGG TTTTTTTEEEEEEEEEEE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  51   TRQQGATLAFLTLRQQASLIQGLVKANKEGTISKNMVKWAGSLNLESIVL  100          1ASY
STR       EEE TTTEEEEEEEETTEEEEEEEE TTTTTTTHHHHHHHHH TTTEEEE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  101  VRGIVKKVDEPIKSATVQNLEIHITKIYTISETPEALPILLEDASRSEAE  150          1ASY
STR       EEEEEEETTTTTTTTTTTTEEEEEEEEEEEET TTTT   HHHHH  HHH               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  151  AEAAGLPVVNLDTRLDYRVIDLRTVTNQAIFRIQAGVCELFREYLATKKF  200          1ASY
STR       HHHH      HHHHHHHHHHHHH HHHHHHHHHHHHHH HHHHHHGGG                 1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  201  TEVHTPKLLGAPSEGGSSVFEVTYFKGKAYLAQSPQFNKQQLIVADFERV  250          1ASY
STR              EE  TTTTTTT EEEEETTEEEEETTTTHHHHHHHHHH TTTE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  251  YEIGPVFRAENSNTHRHMTEFTGLDMEMAFEEHYHEVLDTLSELFVFIFS  300          1ASY
STR       EEEEEEE      BTTBTTEEEEEEEE  TTTTHHHHHHHHHHHHHHHHH               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  301  ELPKRFAHEIELVRKQYPVEEFKLPKDGKMVRLTYKEGIEMLRAAGKEIG  350          1ASY
STR       HHHHHHHHHHHHHHHTTT      TTTT  EEE HHHHHHHHHH     T               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  351  DFEDLSTENEKFLGKLVRDKYDTDFYILDKFPLEIRPFYTMPDPANPKYS  400          1ASY
STR       TTT   HHHHHHHHHHHHHHH TTEEEETTTTTTTTTTTB EETTEEEEE               1ASY
REM                                                                        1ASY
REM                .         .         .         .         .               1ASY
SEQ  401  NSYDFFMRGEEILSGAQRIHDHALLQERMKAHGLSPEDPGLKDYCDGFSY  450          1ASY
STR       TEEEEEETTEEEEEEEEE   HHHHHHHHHHH  TTTTGGGHHHHHHHHH               1ASY
REM                                                                        1ASY
REM                .         .         .         .                         1ASY
SEQ  451  GCPPHAGGGIGLERVVMFYLDLKNIRRASLFPRDPKRLRP            490          1ASY
STR           EEEEEEBHHHHHHHHH    GGG TTTT BTTB                            1ASY
REM                                                                        1ASY
REM                                                                        1ASY
REM                                                                        1ASY
LOC  AlphaHelix   LYS   151 A      GLY    158 A                            1ASY
LOC  AlphaHelix   LEU   208 A      SER    212 A                            1ASY
LOC  AlphaHelix   GLU   215 A      ALA    220 A                            1ASY
LOC  AlphaHelix   LEU   228 A      ASP    233 A                            1ASY
LOC  AlphaHelix   ARG   235 A      LEU    239 A                            1ASY
LOC  AlphaHelix   THR   243 A      LYS    265 A                            1ASY
LOC  AlphaHelix   GLN   303 A      ALA    312 A                            1ASY
LOC  AlphaHelix   TYR   351 A      ARG    381 A                            1ASY
LOC  AlphaHelix   TYR   402 A      ALA    412 A                            1ASY
LOC  AlphaHelix   THR   424 A      TYR    438 A                            1ASY
LOC  AlphaHelix   HIS   489 A      HIS    499 A                            1ASY
LOC  AlphaHelix   PRO   506 A      TYR    517 A                            1ASY
LOC  AlphaHelix   LEU   529 A      LEU    537 A                            1ASY
LOC  AlphaHelix   LYS   151 B      SER    159 B                            1ASY
LOC  AlphaHelix   LEU   208 B      SER    212 B                            1ASY
LOC  AlphaHelix   GLU   215 B      ALA    221 B                            1ASY
LOC  AlphaHelix   LEU   228 B      ARG    240 B                            1ASY
LOC  AlphaHelix   VAL   242 B      CYS    255 B                            1ASY
LOC  AlphaHelix   LEU   257 B      LEU    262 B                            1ASY
LOC  AlphaHelix   GLN   303 B      ALA    312 B                            1ASY
LOC  AlphaHelix   TYR   351 B      LYS    382 B                            1ASY
LOC  AlphaHelix   TYR   402 B      ALA    411 B                            1ASY
LOC  AlphaHelix   THR   424 B      TYR    438 B                            1ASY
LOC  AlphaHelix   HIS   489 B      HIS    499 B                            1ASY
LOC  AlphaHelix   LYS   509 B      TYR    517 B                            1ASY
LOC  AlphaHelix   LEU   529 B      LEU    537 B                            1ASY
LOC  310Helix     PHE    96 A      ASP     98 A                            1ASY
LOC  310Helix     ILE   542 A      ALA    545 A                            1ASY
LOC  310Helix     ASP    85 B      ASP     87 B                            1ASY
LOC  310Helix     PHE    96 B      ASP     98 B                            1ASY
LOC  310Helix     ALA   263 B      LYS    265 B                            1ASY
LOC  310Helix     PRO   506 B      LEU    508 B                            1ASY
LOC  310Helix     ILE   542 B      ARG    544 B                            1ASY
LOC  Strand       TYR    75 A      LYS     77 A                            1ASY
LOC  Strand       LEU   110 A      GLY    122 A                            1ASY
LOC  Strand       LEU   125 A      ARG    131 A                            1ASY
LOC  Strand       LEU   136 A      LYS    142 A                            1ASY
LOC  Strand       SER   164 A      LYS    174 A                            1ASY
LOC  Strand       LEU   187 A      ILE    197 A                            1ASY
LOC  Strand       THR   268 A      GLU    269 A                            1ASY
LOC  Strand       LEU   275 A      LEU    276 A                            1ASY
LOC  Strand       PHE   287 A      THR    290 A                            1ASY
LOC  Strand       TYR   297 A      LEU    298 A                            1ASY
LOC  Strand       ARG   316 A      PHE    324 A                            1ASY
LOC  Strand       GLU   337 A      ALA    346 A                            1ASY
LOC  Strand       VAL   398 A      THR    401 A                            1ASY
LOC  Strand       PHE   442 A      ASP    446 A                            1ASY
LOC  Strand       SER   469 A      MET    474 A                            1ASY
LOC  Strand       GLU   477 A      ARG    485 A                            1ASY
LOC  Strand       HIS   522 A      GLY    528 A                            1ASY
LOC  Strand       TYR    75 B      LYS     77 B                            1ASY
LOC  Strand       LYS   107 B      GLN    120 B                            1ASY
LOC  Strand       LEU   125 B      GLN    132 B                            1ASY
LOC  Strand       SER   135 B      LYS    142 B                            1ASY
LOC  Strand       SER   164 B      LYS    174 B                            1ASY
LOC  Strand       LEU   187 B      SER    198 B                            1ASY
LOC  Strand       LEU   275 B      LEU    276 B                            1ASY
LOC  Strand       PHE   287 B      TYR    291 B                            1ASY
LOC  Strand       GLY   294 B      LEU    298 B                            1ASY
LOC  Strand       VAL   317 B      PHE    324 B                            1ASY
LOC  Strand       GLU   337 B      GLU    344 B                            1ASY
LOC  Strand       VAL   398 B      LEU    400 B                            1ASY
LOC  Strand       PHE   442 B      LEU    445 B                            1ASY
LOC  Strand       PRO   459 B      ASP    460 B                            1ASY
LOC  Strand       ASN   463 B      SER    467 B                            1ASY
LOC  Strand       SER   469 B      MET    474 B                            1ASY
LOC  Strand       GLU   477 B      ARG    485 B                            1ASY
LOC  Strand       HIS   522 B      ILE    527 B                            1ASY
LOC  TurnIV       ASP    69 A      LYS     72 A                            1ASY
LOC  TurnI        ALA    71 A      ASN     74 A                            1ASY
LOC  TurnIV       LYS    72 A      TYR     75 A                            1ASY
LOC  TurnI        ARG    84 A      ASP     87 A                            1ASY
LOC  TurnI        ASP    85 A      ARG     88 A                            1ASY
LOC  TurnIV       ASP   100 A      LYS    103 A                            1ASY
LOC  TurnIV       GLU   101 A      ASP    104 A                            1ASY
LOC  TurnIV       ALA   102 A      SER    105 A                            1ASY
LOC  TurnIV       ASP   104 A      LYS    107 A                            1ASY
LOC  TurnIV       GLY   122 A      LEU    125 A                            1ASY
LOC  TurnIV       GLN   132 A      SER    135 A                            1ASY
LOC  TurnI        ASN   144 A      GLY    147 A                            1ASY
LOC  TurnVIII     GLY   147 A      SER    150 A                            1ASY
LOC  TurnII       ASN   161 A      SER    164 A                            1ASY
LOC  TurnVIII     VAL   175 A      PRO    178 A                            1ASY
LOC  TurnVIII     ILE   179 A      ALA    182 A                            1ASY
LOC  TurnIV       ALA   182 A      GLN    185 A                            1ASY
LOC  TurnIV       VAL   184 A      LEU    187 A                            1ASY
LOC  TurnIV       ILE   191 A      ILE    194 A                            1ASY
LOC  TurnIV       THR   196 A      GLU    199 A                            1ASY
LOC  TurnIV       PRO   201 A      LEU    204 A                            1ASY
LOC  TurnIV       LEU   204 A      LEU    207 A                            1ASY
LOC  TurnIV       PRO   273 A      LEU    276 A                            1ASY
LOC  TurnIV       PRO   279 A      GLY    282 A                            1ASY
LOC  TurnIV       SER   280 A      GLY    283 A                            1ASY
LOC  TurnIV       GLY   282 A      SER    285 A                            1ASY
LOC  TurnIV       GLY   283 A      VAL    286 A                            1ASY
LOC  TurnIV       THR   290 A      LYS    293 A                            1ASY
LOC  TurnIV       TYR   291 A      GLY    294 A                            1ASY
LOC  TurnIV       ALA   299 A      PRO    302 A                            1ASY
LOC  TurnIV       PHE   314 A      VAL    317 A                            1ASY
LOC  TurnIV       THR   331 A      HIS    334 A                            1ASY
LOC  TurnIV       MET   335 A      PHE    338 A                            1ASY
LOC  TurnIV       PHE   347 A      HIS    350 A                            1ASY
LOC  TurnIV       ARG   381 A      TYR    384 A                            1ASY
LOC  TurnIV       LYS   382 A      PRO    385 A                            1ASY
LOC  TurnI        PRO   392 A      GLY    395 A                            1ASY
LOC  TurnIV       GLY   417 A      GLU    420 A                            1ASY
LOC  TurnII       PRO   449 A      ILE    452 A                            1ASY
LOC  TurnIV       LEU   450 A      ARG    453 A                            1ASY
LOC  TurnIV       GLU   451 A      PRO    454 A                            1ASY
LOC  TurnI        PRO   454 A      THR    457 A                            1ASY
LOC  TurnIV       ASP   460 A      ASN    463 A                            1ASY
LOC  TurnVIII     PRO   461 A      PRO    464 A                            1ASY
LOC  TurnI        ASN   463 A      TYR    466 A                            1ASY
LOC  TurnIV       PRO   464 A      SER    467 A                            1ASY
LOC  TurnIV       PHE   473 A      GLY    476 A                            1ASY
LOC  TurnI'       MET   474 A      GLU    477 A                            1ASY
LOC  TurnI        SER   502 A      ASP    505 A                            1ASY
LOC  TurnIV       SER   546 A      PRO    549 A                            1ASY
LOC  TurnIV       ASP   551 A      ARG    554 A                            1ASY
LOC  GammaClassic  LEU   539 A      ASN    541 A                           1ASY
LOC  TurnI        ASP    69 B      LYS     72 B                            1ASY
LOC  TurnIV       ALA    71 B      ASN     74 B                            1ASY
LOC  TurnIV       LYS    72 B      TYR     75 B                            1ASY
LOC  TurnI        ASP   100 B      LYS    103 B                            1ASY
LOC  TurnIV       GLU   101 B      ASP    104 B                            1ASY
LOC  TurnIV       ALA   102 B      SER    105 B                            1ASY
LOC  TurnII       ASP   104 B      LYS    107 B                            1ASY
LOC  TurnIV       GLY   122 B      LEU    125 B                            1ASY
LOC  TurnII'      GLN   132 B      SER    135 B                            1ASY
LOC  TurnI        ASN   144 B      GLY    147 B                            1ASY
LOC  TurnIV       GLY   147 B      SER    150 B                            1ASY
LOC  TurnIV       ASN   161 B      SER    164 B                            1ASY
LOC  TurnIV       VAL   175 B      PRO    178 B                            1ASY
LOC  TurnI        ILE   179 B      ALA    182 B                            1ASY
LOC  TurnVIII     ALA   182 B      GLN    185 B                            1ASY
LOC  TurnI        VAL   184 B      LEU    187 B                            1ASY
LOC  TurnVIII     ILE   191 B      ILE    194 B                            1ASY
LOC  TurnVIII     THR   196 B      GLU    199 B                            1ASY
LOC  TurnIV       PRO   201 B      LEU    204 B                            1ASY
LOC  TurnIV       PRO   279 B      GLY    282 B                            1ASY
LOC  TurnII       GLY   282 B      SER    285 B                            1ASY
LOC  TurnIV       TYR   291 B      GLY    294 B                            1ASY
LOC  TurnIV       ALA   299 B      PRO    302 B                            1ASY
LOC  TurnIV       PHE   314 B      VAL    317 B                            1ASY
LOC  TurnIV       THR   331 B      HIS    334 B                            1ASY
LOC  TurnVIII     MET   335 B      PHE    338 B                            1ASY
LOC  TurnIV       PHE   347 B      HIS    350 B                            1ASY
LOC  TurnIV       LYS   382 B      PRO    385 B                            1ASY
LOC  TurnI        PRO   392 B      GLY    395 B                            1ASY
LOC  TurnIV       GLY   417 B      GLU    420 B                            1ASY
LOC  TurnVIII     THR   440 B      TYR    443 B                            1ASY
LOC  TurnI        PRO   449 B      ILE    452 B                            1ASY
LOC  TurnI        LEU   450 B      ARG    453 B                            1ASY
LOC  TurnI        PRO   454 B      THR    457 B                            1ASY
LOC  TurnIV       ASP   460 B      ASN    463 B                            1ASY
LOC  TurnIV       PRO   461 B      PRO    464 B                            1ASY
LOC  TurnIV       ASN   463 B      TYR    466 B                            1ASY
LOC  TurnIV       PRO   464 B      SER    467 B                            1ASY
LOC  TurnIV       PHE   473 B      GLY    476 B                            1ASY
LOC  TurnI'       MET   474 B      GLU    477 B                            1ASY
LOC  TurnI        SER   502 B      ASP    505 B                            1ASY
LOC  TurnIV       SER   546 B      PRO    549 B                            1ASY
LOC  TurnI        ASP   551 B      ARG    554 B                            1ASY
LOC  GammaInv     LEU    80 B      GLN     82 B                            1ASY
LOC  GammaInv     ILE   189 B      ILE    191 B                            1ASY
LOC  GammaInv     ASP   446 B      PHE    448 B                            1ASY
LOC  GammaInv     SER   467 B      SER    469 B                            1ASY
REM                                                                        1ASY
REM  --------------- Detailed secondary structure assignment-------------  1ASY
REM                                                                        1ASY
REM  |---Residue---|    |--Structure--|   |-Phi-|   |-Psi-|  |-Area-|      1ASY
ASG  GLU A   68    1    C          Coil    360.00    120.57     170.7      1ASY
ASG  ASP A   69    2    T          Turn    173.48    175.69      46.7      1ASY
ASG  THR A   70    3    T          Turn    -90.78    -37.47      84.9      1ASY
ASG  ALA A   71    4    T          Turn   -102.30     32.84       2.9      1ASY
ASG  LYS A   72    5    T          Turn    -45.83    -19.08      81.0      1ASY
ASG  ASP A   73    6    T          Turn   -108.49      4.48     119.3      1ASY
ASG  ASN A   74    7    T          Turn    -99.25    -17.58      24.9      1ASY
ASG  TYR A   75    8    E        Strand   -140.18    167.38      32.3      1ASY
ASG  GLY A   76    9    E        Strand    127.52    159.06      16.9      1ASY
ASG  LYS A   77   10    E        Strand    -62.47    124.80     160.6      1ASY
ASG  LEU A   78   11    C          Coil    -79.22    148.11      50.5      1ASY
ASG  PRO A   79   12    C          Coil    -76.04    144.37     102.9      1ASY
ASG  LEU A   80   13    C          Coil    -31.28    123.72      59.4      1ASY
ASG  ILE A   81   14    C          Coil    -74.91    105.54      20.9      1ASY
ASG  GLN A   82   15    C          Coil   -108.28     -3.67      33.3      1ASY
ASG  SER A   83   16    C          Coil     79.34     11.62       0.0      1ASY
ASG  ARG A   84   17    T          Turn    -50.01    119.24     116.9      1ASY
ASG  ASP A   85   18    T          Turn    -44.12    -21.62     110.9      1ASY
ASG  SER A   86   19    T          Turn    -78.50    -19.24      91.1      1ASY
ASG  ASP A   87   20    T          Turn    -70.07    -36.21      53.7      1ASY
ASG  ARG A   88   21    T          Turn    -46.68     85.57     110.0      1ASY
ASG  THR A   89   22    C          Coil    -83.84    -15.79      92.6      1ASY
ASG  GLY A   90   23    C          Coil     54.27     26.62      52.2      1ASY
ASG  GLN A   91   24    C          Coil    -91.22    143.64      82.6      1ASY
ASG  LYS A   92   25    C          Coil    -70.94    117.93     140.8      1ASY
ASG  ARG A   93   26    C          Coil    -94.28    126.29      58.3      1ASY
ASG  VAL A   94   27    C          Coil   -101.03    147.10      35.2      1ASY
ASG  LYS A   95   28    C          Coil    -97.05    138.65     112.0      1ASY
ASG  PHE A   96   29    G      310Helix    -55.58    -44.11       1.7      1ASY
ASG  VAL A   97   30    G      310Helix    -54.30    -20.81      88.6      1ASY
ASG  ASP A   98   31    G      310Helix   -102.11     16.52      92.9      1ASY
ASG  LEU A   99   32    C          Coil    -80.69    146.03      25.6      1ASY
ASG  ASP A  100   33    T          Turn   -133.81    121.45      49.1      1ASY
ASG  GLU A  101   34    T          Turn    -57.80    -21.39     123.6      1ASY
ASG  ALA A  102   35    T          Turn    -90.56    -55.38      73.7      1ASY
ASG  LYS A  103   36    T          Turn    -90.34    -58.39     171.6      1ASY
ASG  ASP A  104   37    T          Turn    -82.05     69.51      37.1      1ASY
ASG  SER A  105   38    T          Turn   -121.12    109.85      26.7      1ASY
ASG  ASP A  106   39    T          Turn     74.89     67.69      67.3      1ASY
ASG  LYS A  107   40    b        Bridge   -125.67    145.10      83.3      1ASY
ASG  GLU A  108   41    C          Coil    -84.35     60.07     107.8      1ASY
ASG  VAL A  109   42    C          Coil    -65.02    166.60      16.5      1ASY
ASG  LEU A  110   43    E        Strand   -139.83    132.53      21.2      1ASY
ASG  PHE A  111   44    E        Strand   -151.50    164.97       2.4      1ASY
ASG  ARG A  112   45    E        Strand   -113.56    137.01      27.0      1ASY
ASG  ALA A  113   46    E        Strand   -161.27    161.75       4.6      1ASY
ASG  ARG A  114   47    E        Strand    -82.92    156.56       7.4      1ASY
ASG  VAL A  115   48    E        Strand    -97.96    101.36       0.4      1ASY
ASG  HIS A  116   49    E        Strand    -76.37    -47.05      24.2      1ASY
ASG  ASN A  117   50    E        Strand   -163.07    146.47      47.7      1ASY
ASG  THR A  118   51    E        Strand   -125.14    141.45      30.2      1ASY
ASG  ARG A  119   52    E        Strand   -135.11    106.26      90.0      1ASY
ASG  GLN A  120   53    E        Strand   -100.01    129.94      74.9      1ASY
ASG  GLN A  121   54    E        Strand    -87.95    -70.70     133.7      1ASY
ASG  GLY A  122   55    E        Strand   -137.79    172.60      33.5      1ASY
ASG  ALA A  123   56    T          Turn    -75.48     57.79      49.0      1ASY
ASG  THR A  124   57    T          Turn   -164.42    -33.21      66.7      1ASY
ASG  LEU A  125   58    E        Strand   -132.62     99.94      38.4      1ASY
ASG  ALA A  126   59    E        Strand   -117.67    137.94       0.0      1ASY
ASG  PHE A  127   60    E        Strand   -118.00    149.71      32.1      1ASY
ASG  LEU A  128   61    E        Strand   -149.47    136.54       0.6      1ASY
ASG  THR A  129   62    E        Strand    -98.88    111.30       5.8      1ASY
ASG  LEU A  130   63    E        Strand    -87.67    136.48       0.4      1ASY
ASG  ARG A  131   64    E        Strand   -116.29    145.65       2.7      1ASY
ASG  GLN A  132   65    T          Turn   -136.28     69.20      36.3      1ASY
ASG  GLN A  133   66    T          Turn     77.34   -117.76      68.7      1ASY
ASG  ALA A  134   67    T          Turn    -97.04     61.15      37.7      1ASY
ASG  SER A  135   68    T          Turn   -161.29    125.14       3.4      1ASY
ASG  LEU A  136   69    E        Strand   -124.77    162.68      22.2      1ASY
ASG  ILE A  137   70    E        Strand   -166.59    163.82       0.2      1ASY
ASG  GLN A  138   71    E        Strand   -123.23    158.17      12.4      1ASY
ASG  GLY A  139   72    E        Strand   -149.57    162.08       0.0      1ASY
ASG  LEU A  140   73    E        Strand   -132.56    135.83      16.1      1ASY
ASG  VAL A  141   74    E        Strand    -97.93    102.14       0.0      1ASY
ASG  LYS A  142   75    E        Strand   -118.18    108.96     110.3      1ASY
ASG  ALA A  143   76    C          Coil    -43.01    153.38      20.8      1ASY
ASG  ASN A  144   77    B        Bridge   -142.17    151.54      44.1      1ASY
ASG  LYS A  145   78    T          Turn    -61.38    -13.95     189.6      1ASY
ASG  GLU A  146   79    T          Turn    -81.40    -11.77     116.9      1ASY
ASG  GLY A  147   80    T          Turn     83.77     -2.63      15.8      1ASY
ASG  THR A  148   81    T          Turn    -64.30    -46.15      54.1      1ASY
ASG  ILE A  149   82    B        Bridge   -122.48    110.63      21.0      1ASY
ASG  SER A  150   83    T          Turn    -90.95   -159.24       0.4      1ASY
ASG  LYS A  151   84    H    AlphaHelix    -91.60    -38.69     107.8      1ASY
ASG  ASN A  152   85    H    AlphaHelix    -60.64    -38.71      58.7      1ASY
ASG  MET A  153   86    H    AlphaHelix    -70.02    -54.41       0.0      1ASY
ASG  VAL A  154   87    H    AlphaHelix    -60.61    -24.15       0.0      1ASY
ASG  LYS A  155   88    H    AlphaHelix    -78.27    -48.98     139.5      1ASY
ASG  TRP A  156   89    H    AlphaHelix    -53.39    -53.86      48.8      1ASY
ASG  ALA A  157   90    H    AlphaHelix    -64.08    -37.32       0.0      1ASY
ASG  GLY A  158   91    H    AlphaHelix    -70.33     -9.65       8.3      1ASY
ASG  SER A  159   92    C          Coil   -119.74      4.82      64.3      1ASY
ASG  LEU A  160   93    C          Coil    -50.44    122.85       9.8      1ASY
ASG  ASN A  161   94    T          Turn    -58.05    146.47      44.3      1ASY
ASG  LEU A  162   95    T          Turn    -58.67    141.81      66.4      1ASY
ASG  GLU A  163   96    T          Turn     84.06    -15.07       8.2      1ASY
ASG  SER A  164   97    E        Strand    -61.24    150.03       0.2      1ASY
ASG  ILE A  165   98    E        Strand    -96.10    133.07       2.6      1ASY
ASG  VAL A  166   99    E        Strand   -128.51    151.87       0.2      1ASY
ASG  LEU A  167  100    E        Strand   -106.05    107.73      17.4      1ASY
ASG  VAL A  168  101    E        Strand   -106.16    130.86       0.0      1ASY
ASG  ARG A  169  102    E        Strand   -120.51    131.62      53.7      1ASY
ASG  GLY A  170  103    E        Strand   -170.93   -165.92       0.0      1ASY
ASG  ILE A  171  104    E        Strand   -122.21    129.59      47.3      1ASY
ASG  VAL A  172  105    E        Strand    -74.31     90.71       0.0      1ASY
ASG  LYS A  173  106    E        Strand    -98.32    141.81      65.7      1ASY
ASG  LYS A  174  107    E        Strand    -66.99    136.21     146.6      1ASY
ASG  VAL A  175  108    T          Turn   -102.82    122.67      28.4      1ASY
ASG  ASP A  176  109    T          Turn    -68.40    -36.62     160.3      1ASY
ASG  GLU A  177  110    T          Turn   -113.68    110.15     133.7      1ASY
ASG  PRO A  178  111    T          Turn    -34.92    137.00      72.2      1ASY
ASG  ILE A  179  112    T          Turn    -96.57    116.03      20.0      1ASY
ASG  LYS A  180  113    T          Turn    -64.60    -34.82     207.8      1ASY
ASG  SER A  181  114    T          Turn   -101.27     81.20      62.3      1ASY
ASG  ALA A  182  115    T          Turn   -178.66    173.98      17.2      1ASY
ASG  THR A  183  116    T          Turn   -120.11    -48.41      67.9      1ASY
ASG  VAL A  184  117    T          Turn    -88.93     59.37      21.8      1ASY
ASG  GLN A  185  118    T          Turn    -73.34     26.63      77.6      1ASY
ASG  ASN A  186  119    T          Turn   -102.62    -29.67      92.8      1ASY
ASG  LEU A  187  120    E        Strand   -146.38    173.09       4.7      1ASY
ASG  GLU A  188  121    E        Strand   -137.89    161.69      19.0      1ASY
ASG  ILE A  189  122    E        Strand    -93.69    124.89       0.0      1ASY
ASG  HIS A  190  123    E        Strand    -92.97     84.61      68.7      1ASY
ASG  ILE A  191  124    E        Strand    -51.93    129.41       4.5      1ASY
ASG  THR A  192  125    E        Strand   -105.19    -38.48      33.5      1ASY
ASG  LYS A  193  126    E        Strand   -149.36    148.26      50.9      1ASY
ASG  ILE A  194  127    E        Strand   -157.58    125.34       1.0      1ASY
ASG  TYR A  195  128    E        Strand   -127.95    164.29      47.5      1ASY
ASG  THR A  196  129    E        Strand    -95.38    122.67       2.3      1ASY
ASG  ILE A  197  130    E        Strand   -106.22     17.72       9.4      1ASY
ASG  SER A  198  131    B        Bridge    160.61    132.97      25.2      1ASY
ASG  GLU A  199  132    T          Turn   -124.04    146.40      96.0      1ASY
ASG  THR A  200  133    C          Coil   -110.48    152.51       5.0      1ASY
ASG  PRO A  201  134    T          Turn    -67.90    142.02      60.9      1ASY
ASG  GLU A  202  135    T          Turn    -62.86    105.76     140.1      1ASY
ASG  ALA A  203  136    T          Turn    103.81     83.80      87.9      1ASY
ASG  LEU A  204  137    T          Turn    -85.42    172.22      22.4      1ASY
ASG  PRO A  205  138    T          Turn    -83.59   -146.38      51.0      1ASY
ASG  ILE A  206  139    T          Turn     45.59    -65.59      19.1      1ASY
ASG  LEU A  207  140    T          Turn     72.80    118.91      77.6      1ASY
ASG  LEU A  208  141    H    AlphaHelix    -55.19    -60.97      11.3      1ASY
ASG  GLU A  209  142    H    AlphaHelix    -52.28    -40.75      89.7      1ASY
ASG  ASP A  210  143    H    AlphaHelix    -62.78    -22.23      44.3      1ASY
ASG  ALA A  211  144    H    AlphaHelix    -89.74    -43.50       0.2      1ASY
ASG  SER A  212  145    H    AlphaHelix    -63.59    -42.63      30.5      1ASY
ASG  ARG A  213  146    C          Coil    -62.03    140.07      39.9      1ASY
ASG  SER A  214  147    C          Coil    -82.29    146.88      28.4      1ASY
ASG  GLU A  215  148    H    AlphaHelix    -46.04    -23.37     133.8      1ASY
ASG  ALA A  216  149    H    AlphaHelix    -70.58    -68.71      71.8      1ASY
ASG  GLU A  217  150    H    AlphaHelix    -63.26    -10.75     101.9      1ASY
ASG  ALA A  218  151    H    AlphaHelix    -80.27    -60.49       4.2      1ASY
ASG  GLU A  219  152    H    AlphaHelix    -60.89    -20.40     177.4      1ASY
ASG  ALA A  220  153    H    AlphaHelix    -96.14      7.08      85.8      1ASY
ASG  ALA A  221  154    C          Coil   -132.99     -4.08      47.6      1ASY
ASG  GLY A  222  155    C          Coil     85.00    -31.67      72.7      1ASY
ASG  LEU A  223  156    C          Coil    -43.14    157.80      81.1      1ASY
ASG  PRO A  224  157    C          Coil   -102.32    167.91      65.4      1ASY
ASG  VAL A  225  158    C          Coil   -137.75    122.87      29.1      1ASY
ASG  VAL A  226  159    C          Coil    -59.99    136.07      18.7      1ASY
ASG  ASN A  227  160    C          Coil    -77.49    150.67     107.7      1ASY
ASG  LEU A  228  161    H    AlphaHelix    -45.59    -58.42      34.7      1ASY
ASG  ASP A  229  162    H    AlphaHelix    -51.55    -52.02      82.3      1ASY
ASG  THR A  230  163    H    AlphaHelix    -68.79    -25.82      58.1      1ASY
ASG  ARG A  231  164    H    AlphaHelix    -67.14    -30.37      12.2      1ASY
ASG  LEU A  232  165    H    AlphaHelix    -76.49    -44.68       4.0      1ASY
ASG  ASP A  233  166    H    AlphaHelix    -55.15    -15.41      40.8      1ASY
ASG  TYR A  234  167    C          Coil   -133.55     36.15      70.6      1ASY
ASG  ARG A  235  168    H    AlphaHelix    -43.73    -30.16       4.6      1ASY
ASG  VAL A  236  169    H    AlphaHelix    -68.52    -32.34       9.4      1ASY
ASG  ILE A  237  170    H    AlphaHelix    -85.20    -42.78       1.8      1ASY
ASG  ASP A  238  171    H    AlphaHelix    -54.13    -50.96       3.0      1ASY
ASG  LEU A  239  172    H    AlphaHelix    -55.14     -2.89       0.0      1ASY
ASG  ARG A  240  173    C          Coil    -87.43    -20.95       0.3      1ASY
ASG  THR A  241  174    C          Coil    -66.43    141.54       2.3      1ASY
ASG  VAL A  242  175    C          Coil    -44.87    -48.20      38.2      1ASY
ASG  THR A  243  176    H    AlphaHelix    -51.66    -61.11       8.8      1ASY
ASG  ASN A  244  177    H    AlphaHelix    -55.85    -34.84       7.0      1ASY
ASG  GLN A  245  178    H    AlphaHelix    -80.10     17.05      23.6      1ASY
ASG  ALA A  246  179    H    AlphaHelix   -128.95    -42.77       2.4      1ASY
ASG  ILE A  247  180    H    AlphaHelix    -54.56    -26.79       0.2      1ASY
ASG  PHE A  248  181    H    AlphaHelix    -94.02    -24.69       5.4      1ASY
ASG  ARG A  249  182    H    AlphaHelix    -72.96    -21.32      87.9      1ASY
ASG  ILE A  250  183    H    AlphaHelix    -80.52    -52.51       0.8      1ASY
ASG  GLN A  251  184    H    AlphaHelix    -49.20    -34.32       4.8      1ASY
ASG  ALA A  252  185    H    AlphaHelix    -66.36    -61.21       6.0      1ASY
ASG  GLY A  253  186    H    AlphaHelix    -38.29    -51.77       0.0      1ASY
ASG  VAL A  254  187    H    AlphaHelix    -51.34    -61.18       1.2      1ASY
ASG  CYS A  255  188    H    AlphaHelix    -91.22     83.62       0.2      1ASY
ASG  GLU A  256  189    H    AlphaHelix    172.05    -25.22      58.9      1ASY
ASG  LEU A  257  190    H    AlphaHelix    -86.77    -49.31       0.0      1ASY
ASG  PHE A  258  191    H    AlphaHelix    -52.66    -36.07       0.4      1ASY
ASG  ARG A  259  192    H    AlphaHelix    -71.93    -55.65      23.6      1ASY
ASG  GLU A  260  193    H    AlphaHelix    -45.90    -43.11      85.7      1ASY
ASG  TYR A  261  194    H    AlphaHelix    -77.11    -47.00      13.7      1ASY
ASG  LEU A  262  195    H    AlphaHelix    -57.30    -26.34       0.2      1ASY
ASG  ALA A  263  196    H    AlphaHelix    -67.60    -41.09      50.0      1ASY
ASG  THR A  264  197    H    AlphaHelix    -60.25    -25.82      98.9      1ASY
ASG  LYS A  265  198    H    AlphaHelix    -99.13     25.53      46.2      1ASY
ASG  LYS A  266  199    C          Coil     50.93     58.30     169.0      1ASY
ASG  PHE A  267  200    C          Coil   -101.59    144.06      14.0      1ASY
ASG  THR A  268  201    E        Strand   -111.03    127.97      24.9      1ASY
ASG  GLU A  269  202    E        Strand    -64.66    126.30      11.9      1ASY
ASG  VAL A  270  203    C          Coil   -116.69    165.08       5.2      1ASY
ASG  HIS A  271  204    C          Coil   -135.07    118.66      16.4      1ASY
ASG  THR A  272  205    C          Coil   -122.93    158.90       5.5      1ASY
ASG  PRO A  273  206    T          Turn    -54.55    133.48       9.9      1ASY
ASG  LYS A  274  207    T          Turn    -97.70    -21.42       7.0      1ASY
ASG  LEU A  275  208    E        Strand    -85.06    115.59       0.0      1ASY
ASG  LEU A  276  209    E        Strand   -113.33    143.72      29.5      1ASY
ASG  GLY A  277  210    C          Coil    -58.31    -23.32      18.9      1ASY
ASG  ALA A  278  211    C          Coil   -166.51    167.64      12.3      1ASY
ASG  PRO A  279  212    T          Turn    -76.82     76.11      39.7      1ASY
ASG  SER A  280  213    T          Turn    -47.09    105.51      27.8      1ASY
ASG  GLU A  281  214    T          Turn     80.24    -48.41      92.1      1ASY
ASG  GLY A  282  215    T          Turn    101.88     36.15      24.7      1ASY
ASG  GLY A  283  216    T          Turn    -25.35    -51.60      46.4      1ASY
ASG  SER A  284  217    T          Turn   -152.79     61.88      15.3      1ASY
ASG  SER A  285  218    T          Turn     67.10    -43.70      89.9      1ASY
ASG  VAL A  286  219    T          Turn     64.46    132.42      18.4      1ASY
ASG  PHE A  287  220    E        Strand    -78.58    123.46       8.3      1ASY
ASG  GLU A  288  221    E        Strand    -84.45    119.52      60.1      1ASY
ASG  VAL A  289  222    E        Strand   -103.50    143.54       0.0      1ASY
ASG  THR A  290  223    E        Strand    -89.75    110.67      67.7      1ASY
ASG  TYR A  291  224    B        Bridge   -101.68    127.12       7.3      1ASY
ASG  PHE A  292  225    T          Turn     -2.17     87.69      41.2      1ASY
ASG  LYS A  293  226    T          Turn     66.83     22.12     196.2      1ASY
ASG  GLY A  294  227    B        Bridge   -167.58    172.56      36.0      1ASY
ASG  LYS A  295  228    C          Coil    -75.70   -165.51     107.9      1ASY
ASG  ALA A  296  229    C          Coil    165.21    158.31       0.0      1ASY
ASG  TYR A  297  230    E        Strand   -139.59    151.89      37.9      1ASY
ASG  LEU A  298  231    E        Strand    -90.84    136.79       0.3      1ASY
ASG  ALA A  299  232    T          Turn    -67.27    118.08       6.4      1ASY
ASG  GLN A  300  233    T          Turn    -67.40    -21.07      16.3      1ASY
ASG  SER A  301  234    T          Turn   -176.20    142.57      42.5      1ASY
ASG  PRO A  302  235    T          Turn    -75.92     37.85       8.7      1ASY
ASG  GLN A  303  236    H    AlphaHelix    -60.08    -72.12      16.8      1ASY
ASG  PHE A  304  237    H    AlphaHelix    -48.82    -52.84      31.0      1ASY
ASG  ASN A  305  238    H    AlphaHelix    -58.23    -30.31      15.4      1ASY
ASG  LYS A  306  239    H    AlphaHelix    -70.25    -43.84       0.6      1ASY
ASG  GLN A  307  240    H    AlphaHelix    -65.07    -53.89       0.0      1ASY
ASG  GLN A  308  241    H    AlphaHelix    -57.13    -16.17      12.6      1ASY
ASG  LEU A  309  242    H    AlphaHelix    -88.53    -17.53       0.0      1ASY
ASG  ILE A  310  243    H    AlphaHelix    -79.68    -50.52       1.0      1ASY
ASG  VAL A  311  244    H    AlphaHelix    -61.77    -30.05       0.0      1ASY
ASG  ALA A  312  245    H    AlphaHelix    -77.40     19.35       0.2      1ASY
ASG  ASP A  313  246    C          Coil     61.82     34.08      12.0      1ASY
ASG  PHE A  314  247    T          Turn    -86.77    -24.23       3.4      1ASY
ASG  GLU A  315  248    T          Turn     76.35    -76.32      30.5      1ASY
ASG  ARG A  316  249    E        Strand   -121.97    104.20      70.8      1ASY
ASG  VAL A  317  250    E        Strand   -127.00    141.65       0.0      1ASY
ASG  TYR A  318  251    E        Strand   -135.58    153.11      12.6      1ASY
ASG  GLU A  319  252    E        Strand   -144.76    127.60       6.5      1ASY
ASG  ILE A  320  253    E        Strand   -108.10    107.88      13.6      1ASY
ASG  GLY A  321  254    E        Strand   -170.79   -178.01       7.4      1ASY
ASG  PRO A  322  255    E        Strand    -48.67    153.26      11.8      1ASY
ASG  VAL A  323  256    E        Strand   -146.60    125.41       3.2      1ASY
ASG  PHE A  324  257    E        Strand   -115.17     95.48       0.5      1ASY
ASG  ARG A  325  258    C          Coil    -86.38    151.44      94.4      1ASY
ASG  ALA A  326  259    C          Coil   -137.96     27.95       7.7      1ASY
ASG  GLU A  327  260    C          Coil    -82.45    148.28     117.0      1ASY
ASG  ASN A  328  261    C          Coil    -74.42    101.18     104.9      1ASY
ASG  SER A  329  262    C          Coil   -139.18     99.03      24.4      1ASY
ASG  ASN A  330  263    C          Coil    -89.48    111.68      91.7      1ASY
ASG  THR A  331  264    T          Turn   -155.10    172.41      44.6      1ASY
ASG  HIS A  332  265    T          Turn    -94.28      0.09      67.0      1ASY
ASG  ARG A  333  266    T          Turn   -120.80    -12.24      44.0      1ASY
ASG  HIS A  334  267    T          Turn   -108.45    119.41      58.6      1ASY
ASG  MET A  335  268    T          Turn   -102.44   -171.27      21.8      1ASY
ASG  THR A  336  269    T          Turn   -122.39    -11.61       2.4      1ASY
ASG  GLU A  337  270    E        Strand   -149.54    123.53      11.7      1ASY
ASG  PHE A  338  271    E        Strand   -136.48    169.92      44.9      1ASY
ASG  THR A  339  272    E        Strand    -98.79    112.89       7.0      1ASY
ASG  GLY A  340  273    E        Strand    -81.87    155.91       1.7      1ASY
ASG  LEU A  341  274    E        Strand   -126.07    105.85       0.2      1ASY
ASG  ASP A  342  275    E        Strand   -113.52    154.04      13.6      1ASY
ASG  MET A  343  276    E        Strand   -158.51    142.11       2.5      1ASY
ASG  GLU A  344  277    E        Strand   -143.51    138.90       2.0      1ASY
ASG  MET A  345  278    E        Strand   -147.47    148.38       5.4      1ASY
ASG  ALA A  346  279    E        Strand    -89.34    124.83       3.8      1ASY
ASG  PHE A  347  280    T          Turn   -111.95    164.09       3.1      1ASY
ASG  GLU A  348  281    T          Turn    -79.39    -70.07      33.7      1ASY
ASG  GLU A  349  282    T          Turn   -114.18    -40.16      26.8      1ASY
ASG  HIS A  350  283    T          Turn   -130.66    137.03       2.8      1ASY
ASG  TYR A  351  284    H    AlphaHelix    -59.84    -21.60       0.0      1ASY
ASG  HIS A  352  285    H    AlphaHelix    -62.83     -6.10      34.9      1ASY
ASG  GLU A  353  286    H    AlphaHelix    -71.57    -37.08      45.6      1ASY
ASG  VAL A  354  287    H    AlphaHelix    -71.68    -57.50       0.0      1ASY
ASG  LEU A  355  288    H    AlphaHelix    -46.18    -50.16       0.0      1ASY
ASG  ASP A  356  289    H    AlphaHelix    -57.27    -34.62      58.9      1ASY
ASG  THR A  357  290    H    AlphaHelix    -69.72    -42.20       6.6      1ASY
ASG  LEU A  358  291    H    AlphaHelix    -62.48    -63.88       0.4      1ASY
ASG  SER A  359  292    H    AlphaHelix    -46.11    -37.70       9.4      1ASY
ASG  GLU A  360  293    H    AlphaHelix    -76.52    -23.45      94.7      1ASY
ASG  LEU A  361  294    H    AlphaHelix    -61.28    -60.13       0.4      1ASY
ASG  PHE A  362  295    H    AlphaHelix    -53.79    -41.02       0.0      1ASY
ASG  VAL A  363  296    H    AlphaHelix    -58.72    -25.14      50.9      1ASY
ASG  PHE A  364  297    H    AlphaHelix    -79.16    -49.80      44.2      1ASY
ASG  ILE A  365  298    H    AlphaHelix    -53.67    -66.69       0.0      1ASY
ASG  PHE A  366  299    H    AlphaHelix    -52.57    -27.04       4.4      1ASY
ASG  SER A  367  300    H    AlphaHelix    -96.09     -7.95      58.5      1ASY
ASG  GLU A  368  301    H    AlphaHelix   -108.13    -24.25      28.1      1ASY
ASG  LEU A  369  302    H    AlphaHelix    -53.33    -59.77       0.8      1ASY
ASG  PRO A  370  303    H    AlphaHelix    -54.81    -40.25      55.4      1ASY
ASG  LYS A  371  304    H    AlphaHelix    -68.50    -36.00     143.0      1ASY
ASG  ARG A  372  305    H    AlphaHelix    -95.83    -31.40      99.5      1ASY
ASG  PHE A  373  306    H    AlphaHelix   -125.30     49.50       6.4      1ASY
ASG  ALA A  374  307    H    AlphaHelix    -59.60    -61.97      62.0      1ASY
ASG  HIS A  375  308    H    AlphaHelix    -47.82    -48.68      98.4      1ASY
ASG  GLU A  376  309    H    AlphaHelix    -64.33    -26.22      43.7      1ASY
ASG  ILE A  377  310    H    AlphaHelix    -79.78    -30.58      19.0      1ASY
ASG  GLU A  378  311    H    AlphaHelix    -61.18    -59.39      98.1      1ASY
ASG  LEU A  379  312    H    AlphaHelix    -51.92    -36.54      19.6      1ASY
ASG  VAL A  380  313    H    AlphaHelix    -74.58    -36.47       0.0      1ASY
ASG  ARG A  381  314    H    AlphaHelix    -54.99    -51.28      52.1      1ASY
ASG  LYS A  382  315    T          Turn    -76.31     70.81     126.2      1ASY
ASG  GLN A  383  316    T          Turn    164.86    -34.12      21.7      1ASY
ASG  TYR A  384  317    T          Turn   -135.61     93.20      23.3      1ASY
ASG  PRO A  385  318    T          Turn    -90.87    117.85     103.9      1ASY
ASG  VAL A  386  319    C          Coil   -142.61    168.90      29.4      1ASY
ASG  GLU A  387  320    C          Coil    -82.82    148.74     109.6      1ASY
ASG  GLU A  388  321    C          Coil    -46.86    152.65     160.8      1ASY
ASG  PHE A  389  322    C          Coil    -50.52    -55.39       8.5      1ASY
ASG  LYS A  390  323    C          Coil     78.84     91.93      61.0      1ASY
ASG  LEU A  391  324    C          Coil   -110.10    150.09      54.3      1ASY
ASG  PRO A  392  325    T          Turn    -43.31    139.69      10.6      1ASY
ASG  LYS A  393  326    T          Turn    -49.71    -44.26     159.9      1ASY
ASG  ASP A  394  327    T          Turn    -76.63    -44.87     123.9      1ASY
ASG  GLY A  395  328    T          Turn    128.37      2.85      40.4      1ASY
ASG  LYS A  396  329    C          Coil    -96.09    104.26     153.1      1ASY
ASG  MET A  397  330    C          Coil    -52.25    135.33      25.5      1ASY
ASG  VAL A  398  331    E        Strand    -76.45    117.26      14.8      1ASY
ASG  ARG A  399  332    E        Strand   -113.02    126.08      83.2      1ASY
ASG  LEU A  400  333    E        Strand   -128.07    167.63       4.8      1ASY
ASG  THR A  401  334    E        Strand   -104.72    163.98      44.7      1ASY
ASG  TYR A  402  335    H    AlphaHelix    -60.90    -39.99       2.6      1ASY
ASG  LYS A  403  336    H    AlphaHelix    -64.27    -40.02      94.4      1ASY
ASG  GLU A  404  337    H    AlphaHelix    -61.86    -49.43      76.7      1ASY
ASG  GLY A  405  338    H    AlphaHelix    -55.24    -52.43       0.8      1ASY
ASG  ILE A  406  339    H    AlphaHelix    -56.72    -30.32       4.9      1ASY
ASG  GLU A  407  340    H    AlphaHelix    -59.06    -62.93     125.9      1ASY
ASG  MET A  408  341    H    AlphaHelix    -45.24    -56.50      28.3      1ASY
ASG  LEU A  409  342    H    AlphaHelix    -50.86    -49.93       0.0      1ASY
ASG  ARG A  410  343    H    AlphaHelix    -61.45    -41.14     104.5      1ASY
ASG  ALA A  411  344    H    AlphaHelix    -57.33    -55.96      87.4      1ASY
ASG  ALA A  412  345    H    AlphaHelix    -70.69     33.30      56.1      1ASY
ASG  GLY A  413  346    C          Coil     69.99     -3.68      63.9      1ASY
ASG  LYS A  414  347    C          Coil    -68.90    137.12      59.9      1ASY
ASG  GLU A  415  348    C          Coil   -103.19     98.76     185.9      1ASY
ASG  ILE A  416  349    C          Coil   -124.76    159.18       4.9      1ASY
ASG  GLY A  417  350    T          Turn   -117.41     69.25      33.3      1ASY
ASG  ASP A  418  351    T          Turn     54.64    -70.84      68.4      1ASY
ASG  PHE A  419  352    T          Turn   -104.86     16.97      74.2      1ASY
ASG  GLU A  420  353    T          Turn    -82.73    159.49     100.9      1ASY
ASG  ASP A  421  354    C          Coil    -90.31    131.28      95.8      1ASY
ASG  LEU A  422  355    C          Coil    -60.09    117.62       7.2      1ASY
ASG  SER A  423  356    C          Coil    -66.48    172.45      46.5      1ASY
ASG  THR A  424  357    H    AlphaHelix    -66.69    -30.39      72.3      1ASY
ASG  GLU A  425  358    H    AlphaHelix    -62.66    -71.54     128.1      1ASY
ASG  ASN A  426  359    H    AlphaHelix    -51.37    -33.95      18.0      1ASY
ASG  GLU A  427  360    H    AlphaHelix    -53.98    -56.79      24.3      1ASY
ASG  LYS A  428  361    H    AlphaHelix    -63.65    -43.91      85.5      1ASY
ASG  PHE A  429  362    H    AlphaHelix    -59.37    -62.49      44.5      1ASY
ASG  LEU A  430  363    H    AlphaHelix    -50.46    -31.93       1.6      1ASY
ASG  GLY A  431  364    H    AlphaHelix    -63.98    -39.18       8.8      1ASY
ASG  LYS A  432  365    H    AlphaHelix    -66.38    -52.02     123.0      1ASY
ASG  LEU A  433  366    H    AlphaHelix    -46.49    -44.50      26.8      1ASY
ASG  VAL A  434  367    H    AlphaHelix    -75.70    -17.38       0.4      1ASY
ASG  ARG A  435  368    H    AlphaHelix    -74.28    -43.80      53.1      1ASY
ASG  ASP A  436  369    H    AlphaHelix    -58.19    -62.39     115.1      1ASY
ASG  LYS A  437  370    H    AlphaHelix    -62.35    -50.66     125.1      1ASY
ASG  TYR A  438  371    H    AlphaHelix    -98.06     -8.44      77.6      1ASY
ASG  ASP A  439  372    C          Coil     65.20     50.70      40.7      1ASY
ASG  THR A  440  373    C          Coil   -151.40    145.11       1.4      1ASY
ASG  ASP A  441  374    C          Coil    -91.09    -22.19      15.0      1ASY
ASG  PHE A  442  375    E        Strand   -104.64    122.10       0.0      1ASY
ASG  TYR A  443  376    E        Strand   -148.60    135.45       2.2      1ASY
ASG  ILE A  444  377    E        Strand    -88.99    135.81       0.0      1ASY
ASG  LEU A  445  378    E        Strand   -121.73     95.90       0.8      1ASY
ASG  ASP A  446  379    E        Strand    -83.61    162.63       4.2      1ASY
ASG  LYS A  447  380    C          Coil     63.46     49.31      29.5      1ASY
ASG  PHE A  448  381    C          Coil    -61.25    152.46       4.2      1ASY
ASG  PRO A  449  382    B        Bridge    -67.04    148.35       0.2      1ASY
ASG  LEU A  450  383    T          Turn    -79.52    157.98      16.0      1ASY
ASG  GLU A  451  384    T          Turn     85.88     -5.04     118.2      1ASY
ASG  ILE A  452  385    T          Turn   -125.23     13.70      49.1      1ASY
ASG  ARG A  453  386    T          Turn   -127.23    154.17      26.0      1ASY
ASG  PRO A  454  387    T          Turn    -58.95    162.29      46.7      1ASY
ASG  PHE A  455  388    T          Turn    -58.85    -42.26       6.5      1ASY
ASG  TYR A  456  389    T          Turn    -73.46     22.59      41.5      1ASY
ASG  THR A  457  390    B        Bridge    -94.87    122.11       0.4      1ASY
ASG  MET A  458  391    C          Coil    -67.29    117.67       0.2      1ASY
ASG  PRO A  459  392    B        Bridge    -64.19    163.90      15.0      1ASY
ASG  ASP A  460  393    T          Turn    -85.75    140.08      15.3      1ASY
ASG  PRO A  461  394    T          Turn    -60.60    -62.74      19.4      1ASY
ASG  ALA A  462  395    T          Turn    -59.77    -23.64      85.0      1ASY
ASG  ASN A  463  396    T          Turn   -158.28    116.38      63.7      1ASY
ASG  PRO A  464  397    T          Turn    -69.28    -17.39      89.5      1ASY
ASG  LYS A  465  398    T          Turn    -70.69    -17.65     119.7      1ASY
ASG  TYR A  466  399    B        Bridge   -107.97   -179.59      13.0      1ASY
ASG  SER A  467  400    B        Bridge   -150.12    163.59       0.0      1ASY
ASG  ASN A  468  401    C          Coil    -83.77     34.37       0.4      1ASY
ASG  SER A  469  402    E        Strand    -90.44    164.20       0.0      1ASY
ASG  TYR A  470  403    E        Strand   -168.58    136.27       0.0      1ASY
ASG  ASP A  471  404    E        Strand   -105.55    153.36       7.8      1ASY
ASG  PHE A  472  405    E        Strand   -108.15    154.95       0.0      1ASY
ASG  PHE A  473  406    E        Strand   -138.58    143.98       0.0      1ASY
ASG  MET A  474  407    E        Strand   -130.50    127.86       0.0      1ASY
ASG  ARG A  475  408    T          Turn     44.96     45.86      29.9      1ASY
ASG  GLY A  476  409    T          Turn     65.59     14.07       3.1      1ASY
ASG  GLU A  477  410    E        Strand   -121.78    135.30       8.4      1ASY
ASG  GLU A  478  411    E        Strand    -59.93    119.85      64.1      1ASY
ASG  ILE A  479  412    E        Strand   -117.30      3.97       5.0      1ASY
ASG  LEU A  480  413    E        Strand   -164.59    157.57       2.8      1ASY
ASG  SER A  481  414    E        Strand   -147.82    117.45      46.7      1ASY
ASG  GLY A  482  415    E        Strand   -124.42   -173.35       2.3      1ASY
ASG  ALA A  483  416    E        Strand    171.35    176.38       1.8      1ASY
ASG  GLN A  484  417    E        Strand   -121.41    123.58       1.0      1ASY
ASG  ARG A  485  418    E        Strand    -96.93    149.36      10.6      1ASY
ASG  ILE A  486  419    C          Coil    -65.91     95.25       0.2      1ASY
ASG  HIS A  487  420    C          Coil    -82.33     13.43       8.0      1ASY
ASG  ASP A  488  421    C          Coil   -112.42    111.87      53.0      1ASY
ASG  HIS A  489  422    H    AlphaHelix    -51.23    -28.39      48.1      1ASY
ASG  ALA A  490  423    H    AlphaHelix    -67.20    -57.49      67.0      1ASY
ASG  LEU A  491  424    H    AlphaHelix    -64.72    -45.82      26.7      1ASY
ASG  LEU A  492  425    H    AlphaHelix    -45.94    -52.82       0.2      1ASY
ASG  GLN A  493  426    H    AlphaHelix    -63.96    -28.62      58.9      1ASY
ASG  GLU A  494  427    H    AlphaHelix    -66.68    -50.89     134.0      1ASY
ASG  ARG A  495  428    H    AlphaHelix    -61.13    -44.04      22.6      1ASY
ASG  MET A  496  429    H    AlphaHelix    -48.73    -37.53       0.0      1ASY
ASG  LYS A  497  430    H    AlphaHelix    -70.43    -39.85     135.8      1ASY
ASG  ALA A  498  431    H    AlphaHelix    -59.67    -29.55      50.8      1ASY
ASG  HIS A  499  432    H    AlphaHelix   -103.44     40.26      46.3      1ASY
ASG  GLY A  500  433    C          Coil     45.43     23.06      72.4      1ASY
ASG  LEU A  501  434    C          Coil    -95.79    175.65      44.9      1ASY
ASG  SER A  502  435    T          Turn   -138.11    128.23      47.3      1ASY
ASG  PRO A  503  436    T          Turn    -64.87     -9.33      26.8      1ASY
ASG  GLU A  504  437    T          Turn    -80.03    -19.66     154.0      1ASY
ASG  ASP A  505  438    T          Turn    -55.20    133.50      56.5      1ASY
ASG  PRO A  506  439    H    AlphaHelix    -53.97    -46.61      73.7      1ASY
ASG  GLY A  507  440    H    AlphaHelix    -62.64    -27.79       8.2      1ASY
ASG  LEU A  508  441    H    AlphaHelix    -92.10    -41.94       0.4      1ASY
ASG  LYS A  509  442    H    AlphaHelix    -33.10    -65.21      82.6      1ASY
ASG  ASP A  510  443    H    AlphaHelix    -58.04    -33.66      51.1      1ASY
ASG  TYR A  511  444    H    AlphaHelix    -63.41    -50.98       4.1      1ASY
ASG  CYS A  512  445    H    AlphaHelix    -64.85    -46.84       1.4      1ASY
ASG  ASP A  513  446    H    AlphaHelix    -58.13    -38.27      56.1      1ASY
ASG  GLY A  514  447    H    AlphaHelix    -57.85    -12.92       1.6      1ASY
ASG  PHE A  515  448    H    AlphaHelix    -85.16    -22.83       5.8      1ASY
ASG  SER A  516  449    H    AlphaHelix    -70.73    -24.92      35.2      1ASY
ASG  TYR A  517  450    H    AlphaHelix    -85.78     11.77      28.7      1ASY
ASG  GLY A  518  451    C          Coil     56.99    127.90       1.3      1ASY
ASG  CYS A  519  452    C          Coil   -137.84    153.32       0.0      1ASY
ASG  PRO A  520  453    C          Coil    -74.12    175.95       2.6      1ASY
ASG  PRO A  521  454    C          Coil    -73.33    144.84       1.6      1ASY
ASG  HIS A  522  455    E        Strand   -150.10    152.40       0.0      1ASY
ASG  ALA A  523  456    E        Strand   -145.68    167.50       0.0      1ASY
ASG  GLY A  524  457    E        Strand    170.26   -171.04       0.0      1ASY
ASG  GLY A  525  458    E        Strand   -164.94    164.37       1.3      1ASY
ASG  GLY A  526  459    E        Strand   -121.07    121.53      28.6      1ASY
ASG  ILE A  527  460    E        Strand   -103.51    148.22       4.1      1ASY
ASG  GLY A  528  461    E        Strand    -98.48    117.00      14.6      1ASY
ASG  LEU A  529  462    H    AlphaHelix    -43.55    -53.88       0.0      1ASY
ASG  GLU A  530  463    H    AlphaHelix    -53.33    -63.63       6.4      1ASY
ASG  ARG A  531  464    H    AlphaHelix    -48.15    -45.45      44.8      1ASY
ASG  VAL A  532  465    H    AlphaHelix    -55.53    -39.20       0.4      1ASY
ASG  VAL A  533  466    H    AlphaHelix    -79.47    -38.25       1.4      1ASY
ASG  MET A  534  467    H    AlphaHelix    -55.05    -58.27       1.0      1ASY
ASG  PHE A  535  468    H    AlphaHelix    -71.59    -22.39       7.6      1ASY
ASG  TYR A  536  469    H    AlphaHelix    -73.04    -39.30      15.5      1ASY
ASG  LEU A  537  470    H    AlphaHelix    -94.93     -3.28       0.0      1ASY
ASG  ASP A  538  471    C          Coil     52.15     71.37      41.1      1ASY
ASG  LEU A  539  472    T          Turn    -96.71      3.44       0.0      1ASY
ASG  LYS A  540  473    T          Turn     56.36    -14.76     103.8      1ASY
ASG  ASN A  541  474    T          Turn   -150.64    128.53      24.1      1ASY
ASG  ILE A  542  475    G      310Helix    -61.71    -36.26       5.6      1ASY
ASG  ARG A  543  476    G      310Helix    -52.63    -29.32      15.4      1ASY
ASG  ARG A  544  477    G      310Helix    -72.48    -13.67      47.1      1ASY
ASG  ALA A  545  478    G      310Helix   -106.28    -14.00       0.0      1ASY
ASG  SER A  546  479    T          Turn   -107.10    134.85       5.0      1ASY
ASG  LEU A  547  480    T          Turn    -70.95     -7.19       5.9      1ASY
ASG  PHE A  548  481    T          Turn   -154.60     69.79       6.7      1ASY
ASG  PRO A  549  482    T          Turn    -40.18    159.45       2.4      1ASY
ASG  ARG A  550  483    C          Coil   -148.00    123.60       1.4      1ASY
ASG  ASP A  551  484    T          Turn   -150.23    173.73       6.6      1ASY
ASG  PRO A  552  485    T          Turn    -42.11    -17.53      16.9      1ASY
ASG  LYS A  553  486    T          Turn   -118.94    -53.94     146.7      1ASY
ASG  ARG A  554  487    T          Turn    -65.35    127.26      28.8      1ASY
ASG  LEU A  555  488    C          Coil   -138.35    -12.36      29.6      1ASY
ASG  ARG A  556  489    C          Coil   -146.31    147.88      84.2      1ASY
ASG  PRO A  557  490    C          Coil    -61.83    360.00      27.3      1ASY
ASG  GLU B   68    1    C          Coil    360.00     24.61     213.5      1ASY
ASG  ASP B   69    2    T          Turn    -56.93    139.43      42.7      1ASY
ASG  THR B   70    3    T          Turn    -36.88    -37.48      98.6      1ASY
ASG  ALA B   71    4    T          Turn   -105.59     -9.18       0.6      1ASY
ASG  LYS B   72    5    T          Turn    -20.12    -44.36      95.7      1ASY
ASG  ASP B   73    6    T          Turn   -111.50     63.18     125.2      1ASY
ASG  ASN B   74    7    T          Turn   -150.05     -2.17      29.3      1ASY
ASG  TYR B   75    8    E        Strand   -154.61    150.90      20.9      1ASY
ASG  GLY B   76    9    E        Strand    144.26   -179.91      15.3      1ASY
ASG  LYS B   77   10    E        Strand    -87.85    117.36     150.8      1ASY
ASG  LEU B   78   11    C          Coil    -61.73    145.43      47.3      1ASY
ASG  PRO B   79   12    C          Coil    -49.07    -34.58     115.3      1ASY
ASG  LEU B   80   13    T          Turn    127.00    121.06      52.1      1ASY
ASG  ILE B   81   14    T          Turn    -81.69     82.66      27.3      1ASY
ASG  GLN B   82   15    T          Turn    -97.69     22.54      47.0      1ASY
ASG  SER B   83   16    C          Coil     48.69     74.62       2.5      1ASY
ASG  ARG B   84   17    C          Coil    -94.68    132.22     126.7      1ASY
ASG  ASP B   85   18    G      310Helix    -47.85    -46.66     105.4      1ASY
ASG  SER B   86   19    G      310Helix    -63.10    -40.06      95.3      1ASY
ASG  ASP B   87   20    G      310Helix    -59.87    -18.34      78.1      1ASY
ASG  ARG B   88   21    C          Coil    -66.51    130.69      95.9      1ASY
ASG  THR B   89   22    C          Coil   -129.38    -34.09      79.5      1ASY
ASG  GLY B   90   23    C          Coil     91.48      6.84      57.2      1ASY
ASG  GLN B   91   24    C          Coil    -63.34    112.31      98.9      1ASY
ASG  LYS B   92   25    C          Coil    -54.67    131.48     178.1      1ASY
ASG  ARG B   93   26    C          Coil   -109.57    146.14      43.1      1ASY
ASG  VAL B   94   27    C          Coil    -97.42    159.97      18.3      1ASY
ASG  LYS B   95   28    C          Coil   -119.63    118.54      67.7      1ASY
ASG  PHE B   96   29    G      310Helix    -45.56    -37.01       0.9      1ASY
ASG  VAL B   97   30    G      310Helix    -64.47     -7.84     106.2      1ASY
ASG  ASP B   98   31    G      310Helix   -104.06    -33.48     113.5      1ASY
ASG  LEU B   99   32    C          Coil    -47.05    117.91      15.2      1ASY
ASG  ASP B  100   33    T          Turn   -114.49    110.63      80.5      1ASY
ASG  GLU B  101   34    T          Turn    -43.96    -48.53      63.5      1ASY
ASG  ALA B  102   35    T          Turn    -70.77     20.83      61.9      1ASY
ASG  LYS B  103   36    T          Turn   -171.14     -3.94     169.4      1ASY
ASG  ASP B  104   37    T          Turn   -120.35     -1.62      39.1      1ASY
ASG  SER B  105   38    T          Turn    -57.78    138.01      26.4      1ASY
ASG  ASP B  106   39    T          Turn     65.17      6.45      89.4      1ASY
ASG  LYS B  107   40    E        Strand    -92.40    119.92     105.3      1ASY
ASG  GLU B  108   41    E        Strand    -64.32    151.05     114.0      1ASY
ASG  VAL B  109   42    E        Strand   -151.26    162.44      13.0      1ASY
ASG  LEU B  110   43    E        Strand   -135.67    144.76      14.4      1ASY
ASG  PHE B  111   44    E        Strand   -163.79    175.66       0.0      1ASY
ASG  ARG B  112   45    E        Strand   -119.43    139.28      14.1      1ASY
ASG  ALA B  113   46    E        Strand   -163.43    166.87       3.6      1ASY
ASG  ARG B  114   47    E        Strand    -97.22    137.21       4.4      1ASY
ASG  VAL B  115   48    E        Strand    -86.25    103.09       0.0      1ASY
ASG  HIS B  116   49    E        Strand    -83.57    -43.08      16.1      1ASY
ASG  ASN B  117   50    E        Strand   -137.65    149.50      45.1      1ASY
ASG  THR B  118   51    E        Strand   -141.15     97.75      38.1      1ASY
ASG  ARG B  119   52    E        Strand   -100.92     90.66      78.2      1ASY
ASG  GLN B  120   53    E        Strand    -84.15     96.63      78.4      1ASY
ASG  GLN B  121   54    C          Coil    -93.84     69.09     119.1      1ASY
ASG  GLY B  122   55    T          Turn     96.37    158.20      42.2      1ASY
ASG  ALA B  123   56    T          Turn    -71.45     16.46      47.8      1ASY
ASG  THR B  124   57    T          Turn   -134.34     13.35      74.0      1ASY
ASG  LEU B  125   58    E        Strand   -163.21    120.36      37.3      1ASY
ASG  ALA B  126   59    E        Strand   -131.96    116.47       0.0      1ASY
ASG  PHE B  127   60    E        Strand    -89.34    142.35      38.9      1ASY
ASG  LEU B  128   61    E        Strand   -132.30    140.56       0.0      1ASY
ASG  THR B  129   62    E        Strand   -110.36    114.89       1.0      1ASY
ASG  LEU B  130   63    E        Strand   -101.73    127.78       0.0      1ASY
ASG  ARG B  131   64    E        Strand   -125.67    139.44       0.0      1ASY
ASG  GLN B  132   65    E        Strand   -141.60    104.92      19.9      1ASY
ASG  GLN B  133   66    T          Turn     73.24   -124.82      51.4      1ASY
ASG  ALA B  134   67    T          Turn   -102.80     40.05      12.1      1ASY
ASG  SER B  135   68    E        Strand   -151.96    135.13      11.8      1ASY
ASG  LEU B  136   69    E        Strand   -137.86    138.87      16.8      1ASY
ASG  ILE B  137   70    E        Strand   -126.36    164.87       0.0      1ASY
ASG  GLN B  138   71    E        Strand   -101.66    133.85       9.2      1ASY
ASG  GLY B  139   72    E        Strand   -138.49    118.89       0.0      1ASY
ASG  LEU B  140   73    E        Strand    -91.26    159.56      10.2      1ASY
ASG  VAL B  141   74    E        Strand   -129.82     82.52       0.0      1ASY
ASG  LYS B  142   75    E        Strand    -93.14    109.89     110.4      1ASY
ASG  ALA B  143   76    C          Coil    -52.16    146.79      21.5      1ASY
ASG  ASN B  144   77    T          Turn   -126.98    165.29      39.4      1ASY
ASG  LYS B  145   78    T          Turn    -56.70    -53.78     169.1      1ASY
ASG  GLU B  146   79    T          Turn    -53.83    -15.08     133.1      1ASY
ASG  GLY B  147   80    T          Turn     84.29      9.48      11.2      1ASY
ASG  THR B  148   81    T          Turn    -65.41    -62.86      64.5      1ASY
ASG  ILE B  149   82    T          Turn    -93.19     86.08      21.6      1ASY
ASG  SER B  150   83    T          Turn    -64.84    167.89       6.2      1ASY
ASG  LYS B  151   84    H    AlphaHelix    -78.69    -36.29     127.3      1ASY
ASG  ASN B  152   85    H    AlphaHelix    -62.34    -25.75     101.2      1ASY
ASG  MET B  153   86    H    AlphaHelix    -76.31    -44.38       0.0      1ASY
ASG  VAL B  154   87    H    AlphaHelix    -57.15    -24.95       0.0      1ASY
ASG  LYS B  155   88    H    AlphaHelix    -63.07    -62.74     125.1      1ASY
ASG  TRP B  156   89    H    AlphaHelix    -50.42    -54.15      53.1      1ASY
ASG  ALA B  157   90    H    AlphaHelix    -58.07    -27.56       0.0      1ASY
ASG  GLY B  158   91    H    AlphaHelix    -88.00    -39.00       2.9      1ASY
ASG  SER B  159   92    H    AlphaHelix    -92.91     28.71      69.9      1ASY
ASG  LEU B  160   93    C          Coil    -72.92    105.81       9.7      1ASY
ASG  ASN B  161   94    T          Turn    -35.44    118.03      39.0      1ASY
ASG  LEU B  162   95    T          Turn    -47.62    146.31      73.4      1ASY
ASG  GLU B  163   96    T          Turn     59.17     64.58       5.6      1ASY
ASG  SER B  164   97    E        Strand   -127.88    154.10       0.2      1ASY
ASG  ILE B  165   98    E        Strand   -104.30    129.00       4.2      1ASY
ASG  VAL B  166   99    E        Strand   -124.82    140.49       0.0      1ASY
ASG  LEU B  167  100    E        Strand    -93.33    130.59      27.1      1ASY
ASG  VAL B  168  101    E        Strand   -140.45    123.72       0.4      1ASY
ASG  ARG B  169  102    E        Strand   -109.84    143.76      65.8      1ASY
ASG  GLY B  170  103    E        Strand   -173.99    164.73       0.0      1ASY
ASG  ILE B  171  104    E        Strand    -97.04    131.16      43.5      1ASY
ASG  VAL B  172  105    E        Strand    -63.66    137.89       0.2      1ASY
ASG  LYS B  173  106    E        Strand   -143.01    138.32      68.6      1ASY
ASG  LYS B  174  107    E        Strand    -86.02    163.56      99.4      1ASY
ASG  VAL B  175  108    T          Turn   -123.42    174.49      35.1      1ASY
ASG  ASP B  176  109    T          Turn   -117.22    -40.18     148.8      1ASY
ASG  GLU B  177  110    T          Turn    -98.09     97.00     154.7      1ASY
ASG  PRO B  178  111    T          Turn    -42.65    137.14      84.6      1ASY
ASG  ILE B  179  112    T          Turn    -85.20    122.64      17.9      1ASY
ASG  LYS B  180  113    T          Turn    -86.56    -27.64     193.3      1ASY
ASG  SER B  181  114    T          Turn    -66.30    -21.91      48.9      1ASY
ASG  ALA B  182  115    T          Turn   -102.62    171.68       6.7      1ASY
ASG  THR B  183  116    T          Turn    -88.57    -42.41      48.6      1ASY
ASG  VAL B  184  117    T          Turn    -94.78    101.14      19.2      1ASY
ASG  GLN B  185  118    T          Turn    -89.82    -20.72      85.0      1ASY
ASG  ASN B  186  119    T          Turn    -85.62     -2.28      79.6      1ASY
ASG  LEU B  187  120    E        Strand   -142.82    169.08       0.8      1ASY
ASG  GLU B  188  121    E        Strand   -159.15    153.17      27.1      1ASY
ASG  ILE B  189  122    E        Strand   -102.85    104.89       0.0      1ASY
ASG  HIS B  190  123    E        Strand    -72.64     86.27      53.1      1ASY
ASG  ILE B  191  124    E        Strand    -51.99    103.63       0.9      1ASY
ASG  THR B  192  125    E        Strand    -89.61    -19.83      32.9      1ASY
ASG  LYS B  193  126    E        Strand   -158.13    144.05      43.3      1ASY
ASG  ILE B  194  127    E        Strand   -155.78    114.37       0.0      1ASY
ASG  TYR B  195  128    E        Strand   -115.01    165.62      59.7      1ASY
ASG  THR B  196  129    E        Strand   -104.85    112.01       0.8      1ASY
ASG  ILE B  197  130    E        Strand    -83.06    -55.60      21.0      1ASY
ASG  SER B  198  131    E        Strand   -124.78    125.70       8.5      1ASY
ASG  GLU B  199  132    T          Turn   -110.65    115.78      94.2      1ASY
ASG  THR B  200  133    C          Coil    -82.11    171.92       6.0      1ASY
ASG  PRO B  201  134    T          Turn    -94.13    163.63      56.0      1ASY
ASG  GLU B  202  135    T          Turn    -22.78    -53.62     158.6      1ASY
ASG  ALA B  203  136    T          Turn   -153.68    138.70      80.4      1ASY
ASG  LEU B  204  137    T          Turn   -115.97    138.52      16.1      1ASY
ASG  PRO B  205  138    C          Coil    -37.79    163.15      55.2      1ASY
ASG  ILE B  206  139    C          Coil     40.64    138.62      21.4      1ASY
ASG  LEU B  207  140    C          Coil   -123.20    143.68      83.3      1ASY
ASG  LEU B  208  141    H    AlphaHelix    -56.12    -38.25       9.2      1ASY
ASG  GLU B  209  142    H    AlphaHelix    -62.76    -44.49      75.9      1ASY
ASG  ASP B  210  143    H    AlphaHelix    -61.83    -52.80      24.5      1ASY
ASG  ALA B  211  144    H    AlphaHelix    -58.13    -29.58       0.3      1ASY
ASG  SER B  212  145    H    AlphaHelix   -100.63     -3.19      30.9      1ASY
ASG  ARG B  213  146    C          Coil    -72.54    128.62      39.2      1ASY
ASG  SER B  214  147    C          Coil    -53.96    174.93      11.1      1ASY
ASG  GLU B  215  148    H    AlphaHelix    -88.43    -46.28     159.2      1ASY
ASG  ALA B  216  149    H    AlphaHelix    -56.91    -65.30      57.1      1ASY
ASG  GLU B  217  150    H    AlphaHelix    -40.32    -64.04     123.5      1ASY
ASG  ALA B  218  151    H    AlphaHelix    -44.13    -43.61       5.2      1ASY
ASG  GLU B  219  152    H    AlphaHelix    -69.26    -50.10     143.7      1ASY
ASG  ALA B  220  153    H    AlphaHelix    -58.10    -57.20      76.7      1ASY
ASG  ALA B  221  154    H    AlphaHelix    -76.17      2.63      71.0      1ASY
ASG  GLY B  222  155    C          Coil     53.02     49.43      59.3      1ASY
ASG  LEU B  223  156    C          Coil   -116.40    158.12      77.7      1ASY
ASG  PRO B  224  157    C          Coil    -60.83    164.02      76.4      1ASY
ASG  VAL B  225  158    C          Coil   -156.38    114.36      47.3      1ASY
ASG  VAL B  226  159    C          Coil    -62.18    135.67      20.1      1ASY
ASG  ASN B  227  160    C          Coil    -75.05    135.85     116.7      1ASY
ASG  LEU B  228  161    H    AlphaHelix    -43.30    -41.96      32.8      1ASY
ASG  ASP B  229  162    H    AlphaHelix    -63.19    -41.51     100.4      1ASY
ASG  THR B  230  163    H    AlphaHelix    -75.43    -34.12      53.3      1ASY
ASG  ARG B  231  164    H    AlphaHelix    -53.88    -50.95      15.2      1ASY
ASG  LEU B  232  165    H    AlphaHelix    -59.07    -33.89       5.6      1ASY
ASG  ASP B  233  166    H    AlphaHelix    -68.51    -20.89      69.5      1ASY
ASG  TYR B  234  167    H    AlphaHelix   -132.62     53.64      83.5      1ASY
ASG  ARG B  235  168    H    AlphaHelix    -66.78    -27.65       4.5      1ASY
ASG  VAL B  236  169    H    AlphaHelix    -66.46    -38.88      10.6      1ASY
ASG  ILE B  237  170    H    AlphaHelix    -75.79    -48.66       0.2      1ASY
ASG  ASP B  238  171    H    AlphaHelix    -55.90    -41.22       4.0      1ASY
ASG  LEU B  239  172    H    AlphaHelix    -57.57    -29.63       0.0      1ASY
ASG  ARG B  240  173    H    AlphaHelix    -54.66    -28.37       0.0      1ASY
ASG  THR B  241  174    C          Coil    -48.58    154.69       0.4      1ASY
ASG  VAL B  242  175    H    AlphaHelix    -67.35    -17.34      26.5      1ASY
ASG  THR B  243  176    H    AlphaHelix    -80.13    -50.45       7.6      1ASY
ASG  ASN B  244  177    H    AlphaHelix    -57.76    -46.73       3.8      1ASY
ASG  GLN B  245  178    H    AlphaHelix    -50.81    -36.56       0.0      1ASY
ASG  ALA B  246  179    H    AlphaHelix    -81.24    -25.53       0.2      1ASY
ASG  ILE B  247  180    H    AlphaHelix    -65.28    -69.12       0.0      1ASY
ASG  PHE B  248  181    H    AlphaHelix    -59.98    -14.78       9.1      1ASY
ASG  ARG B  249  182    H    AlphaHelix    -85.14     -3.37      39.3      1ASY
ASG  ILE B  250  183    H    AlphaHelix   -104.24    -38.67       1.2      1ASY
ASG  GLN B  251  184    H    AlphaHelix    -53.97    -50.97       4.8      1ASY
ASG  ALA B  252  185    H    AlphaHelix    -58.29    -51.35      10.2      1ASY
ASG  GLY B  253  186    H    AlphaHelix    -56.67    -31.55       2.8      1ASY
ASG  VAL B  254  187    H    AlphaHelix    -71.38    -51.54       2.0      1ASY
ASG  CYS B  255  188    H    AlphaHelix    -84.17     53.87       0.0      1ASY
ASG  GLU B  256  189    C          Coil   -155.09     -1.90      78.3      1ASY
ASG  LEU B  257  190    H    AlphaHelix   -113.10    -18.70       0.0      1ASY
ASG  PHE B  258  191    H    AlphaHelix    -65.36    -68.69       0.0      1ASY
ASG  ARG B  259  192    H    AlphaHelix    -50.07    -44.56      14.1      1ASY
ASG  GLU B  260  193    H    AlphaHelix    -64.52    -38.16      79.0      1ASY
ASG  TYR B  261  194    H    AlphaHelix    -71.51    -51.34      18.7      1ASY
ASG  LEU B  262  195    H    AlphaHelix    -54.84    -39.95       0.2      1ASY
ASG  ALA B  263  196    G      310Helix    -65.58    -17.76      54.3      1ASY
ASG  THR B  264  197    G      310Helix    -80.29    -20.76      90.0      1ASY
ASG  LYS B  265  198    G      310Helix   -103.21     19.55      61.3      1ASY
ASG  LYS B  266  199    C          Coil     56.29     47.92     156.8      1ASY
ASG  PHE B  267  200    C          Coil    -89.11    160.85      16.1      1ASY
ASG  THR B  268  201    C          Coil   -129.42    114.75      24.3      1ASY
ASG  GLU B  269  202    C          Coil    -48.50    134.88      14.1      1ASY
ASG  VAL B  270  203    C          Coil   -131.75    170.79       4.1      1ASY
ASG  HIS B  271  204    C          Coil   -141.89     83.54      24.3      1ASY
ASG  THR B  272  205    C          Coil    -80.10    169.73       4.4      1ASY
ASG  PRO B  273  206    C          Coil    -87.43    166.33       7.8      1ASY
ASG  LYS B  274  207    C          Coil   -112.86    -28.89       5.4      1ASY
ASG  LEU B  275  208    E        Strand    -78.21    103.72       0.0      1ASY
ASG  LEU B  276  209    E        Strand    -96.72    157.03      45.7      1ASY
ASG  GLY B  277  210    C          Coil    -80.96    -35.20      31.2      1ASY
ASG  ALA B  278  211    C          Coil   -151.56    140.00      30.1      1ASY
ASG  PRO B  279  212    T          Turn    -58.96    160.60      52.7      1ASY
ASG  SER B  280  213    T          Turn    -97.31   -137.50      54.3      1ASY
ASG  GLU B  281  214    T          Turn    -53.21    -13.72      72.2      1ASY
ASG  GLY B  282  215    T          Turn     92.65    -32.07      44.7      1ASY
ASG  GLY B  283  216    T          Turn    -67.58    112.43      40.9      1ASY
ASG  SER B  284  217    T          Turn    109.24     -7.37      44.1      1ASY
ASG  SER B  285  218    T          Turn     54.60    178.56      56.4      1ASY
ASG  VAL B  286  219    C          Coil   -158.90    150.46      42.2      1ASY
ASG  PHE B  287  220    E        Strand    -83.32    148.92       2.8      1ASY
ASG  GLU B  288  221    E        Strand   -115.23     96.70      67.9      1ASY
ASG  VAL B  289  222    E        Strand    -74.78    125.58       0.0      1ASY
ASG  THR B  290  223    E        Strand    -73.54    148.06      41.9      1ASY
ASG  TYR B  291  224    E        Strand   -140.67     91.32       6.1      1ASY
ASG  PHE B  292  225    T          Turn     74.86    -82.03      62.7      1ASY
ASG  LYS B  293  226    T          Turn   -140.73      5.11     213.2      1ASY
ASG  GLY B  294  227    E        Strand   -113.34   -152.82      35.4      1ASY
ASG  LYS B  295  228    E        Strand   -144.53    146.71      98.7      1ASY
ASG  ALA B  296  229    E        Strand   -133.60    177.01       0.0      1ASY
ASG  TYR B  297  230    E        Strand   -140.77    120.76      44.2      1ASY
ASG  LEU B  298  231    E        Strand    -55.78    136.48       0.9      1ASY
ASG  ALA B  299  232    T          Turn    -72.14     98.31       2.7      1ASY
ASG  GLN B  300  233    T          Turn    -57.62     -1.84      21.6      1ASY
ASG  SER B  301  234    T          Turn    177.27    142.76      42.5      1ASY
ASG  PRO B  302  235    T          Turn    -91.56     43.09       6.0      1ASY
ASG  GLN B  303  236    H    AlphaHelix    -71.42    -53.49      12.2      1ASY
ASG  PHE B  304  237    H    AlphaHelix    -56.93    -61.39      39.0      1ASY
ASG  ASN B  305  238    H    AlphaHelix    -50.62    -40.01      15.4      1ASY
ASG  LYS B  306  239    H    AlphaHelix    -67.56    -14.40       4.4      1ASY
ASG  GLN B  307  240    H    AlphaHelix    -85.13    -49.33       0.0      1ASY
ASG  GLN B  308  241    H    AlphaHelix    -49.32    -53.24       5.2      1ASY
ASG  LEU B  309  242    H    AlphaHelix    -54.22    -24.79       0.0      1ASY
ASG  ILE B  310  243    H    AlphaHelix    -72.58    -36.25       0.0      1ASY
ASG  VAL B  311  244    H    AlphaHelix    -63.59    -47.99       0.2      1ASY
ASG  ALA B  312  245    H    AlphaHelix    -74.57     36.11       0.4      1ASY
ASG  ASP B  313  246    C          Coil     54.00     20.51       8.6      1ASY
ASG  PHE B  314  247    T          Turn    -77.04    -25.59      10.9      1ASY
ASG  GLU B  315  248    T          Turn     72.81    -46.25      32.5      1ASY
ASG  ARG B  316  249    T          Turn   -144.43    115.92      68.7      1ASY
ASG  VAL B  317  250    E        Strand   -124.05    175.66       1.2      1ASY
ASG  TYR B  318  251    E        Strand   -176.40    145.13      11.3      1ASY
ASG  GLU B  319  252    E        Strand   -146.70    153.93      11.0      1ASY
ASG  ILE B  320  253    E        Strand   -133.29    123.94      13.3      1ASY
ASG  GLY B  321  254    E        Strand    175.56    176.45       6.1      1ASY
ASG  PRO B  322  255    E        Strand    -66.99    127.94       6.6      1ASY
ASG  VAL B  323  256    E        Strand   -115.13    120.94       4.4      1ASY
ASG  PHE B  324  257    E        Strand    -99.99    160.43       0.0      1ASY
ASG  ARG B  325  258    C          Coil   -153.95    123.01      84.4      1ASY
ASG  ALA B  326  259    C          Coil   -101.83     17.47      17.7      1ASY
ASG  GLU B  327  260    C          Coil    -64.05    150.87      86.4      1ASY
ASG  ASN B  328  261    C          Coil    -93.32     58.33      89.3      1ASY
ASG  SER B  329  262    C          Coil    -86.47    145.06      38.9      1ASY
ASG  ASN B  330  263    C          Coil   -134.96    107.33      82.2      1ASY
ASG  THR B  331  264    B        Bridge   -160.54    157.46      43.4      1ASY
ASG  HIS B  332  265    T          Turn    -68.74      1.27      63.5      1ASY
ASG  ARG B  333  266    T          Turn   -142.60     25.21      12.3      1ASY
ASG  HIS B  334  267    B        Bridge   -143.50    140.95      68.6      1ASY
ASG  MET B  335  268    T          Turn   -142.58    158.04      18.3      1ASY
ASG  THR B  336  269    T          Turn    -67.76    -46.26       2.2      1ASY
ASG  GLU B  337  270    E        Strand   -120.60    150.46      13.6      1ASY
ASG  PHE B  338  271    E        Strand   -171.98    169.00      38.8      1ASY
ASG  THR B  339  272    E        Strand   -103.67    118.75       9.6      1ASY
ASG  GLY B  340  273    E        Strand    -92.77    144.99       1.3      1ASY
ASG  LEU B  341  274    E        Strand   -116.45     84.94       2.6      1ASY
ASG  ASP B  342  275    E        Strand    -80.85    154.34      12.0      1ASY
ASG  MET B  343  276    E        Strand   -155.20    115.53       0.8      1ASY
ASG  GLU B  344  277    E        Strand   -114.05    129.16       0.2      1ASY
ASG  MET B  345  278    C          Coil   -108.39   -160.25       9.8      1ASY
ASG  ALA B  346  279    C          Coil   -166.03    120.83       2.0      1ASY
ASG  PHE B  347  280    T          Turn   -111.85    173.68       4.0      1ASY
ASG  GLU B  348  281    T          Turn    -82.13    -70.79      41.9      1ASY
ASG  GLU B  349  282    T          Turn   -112.55    -43.41      23.7      1ASY
ASG  HIS B  350  283    T          Turn   -126.19    131.52       3.6      1ASY
ASG  TYR B  351  284    H    AlphaHelix    -53.26    -17.51       0.0      1ASY
ASG  HIS B  352  285    H    AlphaHelix    -65.47    -11.99      31.9      1ASY
ASG  GLU B  353  286    H    AlphaHelix    -72.07    -45.09      50.0      1ASY
ASG  VAL B  354  287    H    AlphaHelix    -66.34    -24.74       0.0      1ASY
ASG  LEU B  355  288    H    AlphaHelix    -76.04    -62.13       0.0      1ASY
ASG  ASP B  356  289    H    AlphaHelix    -45.38    -32.89      68.4      1ASY
ASG  THR B  357  290    H    AlphaHelix    -71.32    -54.01      14.6      1ASY
ASG  LEU B  358  291    H    AlphaHelix    -57.25    -19.99       0.0      1ASY
ASG  SER B  359  292    H    AlphaHelix    -80.15    -61.79      10.4      1ASY
ASG  GLU B  360  293    H    AlphaHelix    -50.22    -31.45     101.9      1ASY
ASG  LEU B  361  294    H    AlphaHelix    -53.10    -50.46       0.4      1ASY
ASG  PHE B  362  295    H    AlphaHelix    -70.02    -44.60       0.6      1ASY
ASG  VAL B  363  296    H    AlphaHelix    -56.06    -37.19      40.9      1ASY
ASG  PHE B  364  297    H    AlphaHelix    -67.03    -52.76      46.9      1ASY
ASG  ILE B  365  298    H    AlphaHelix    -54.91    -43.54       3.4      1ASY
ASG  PHE B  366  299    H    AlphaHelix    -73.58     -3.40      10.7      1ASY
ASG  SER B  367  300    H    AlphaHelix   -107.51    -13.44      53.7      1ASY
ASG  GLU B  368  301    H    AlphaHelix   -110.61    -28.98      39.3      1ASY
ASG  LEU B  369  302    H    AlphaHelix    -48.77    -51.56       1.6      1ASY
ASG  PRO B  370  303    H    AlphaHelix    -70.13    -45.57      49.5      1ASY
ASG  LYS B  371  304    H    AlphaHelix    -52.91    -26.24     143.0      1ASY
ASG  ARG B  372  305    H    AlphaHelix   -122.28    -16.62      85.5      1ASY
ASG  PHE B  373  306    H    AlphaHelix   -127.48     18.09      24.7      1ASY
ASG  ALA B  374  307    H    AlphaHelix    -38.16    -52.22      59.6      1ASY
ASG  HIS B  375  308    H    AlphaHelix    -58.11    -46.49      80.6      1ASY
ASG  GLU B  376  309    H    AlphaHelix    -67.50    -26.77      36.3      1ASY
ASG  ILE B  377  310    H    AlphaHelix    -73.36    -48.96      15.4      1ASY
ASG  GLU B  378  311    H    AlphaHelix    -48.52    -52.39      93.9      1ASY
ASG  LEU B  379  312    H    AlphaHelix    -56.27    -42.96      17.3      1ASY
ASG  VAL B  380  313    H    AlphaHelix    -71.72    -29.44       3.0      1ASY
ASG  ARG B  381  314    H    AlphaHelix    -57.61    -46.77      65.3      1ASY
ASG  LYS B  382  315    H    AlphaHelix    -53.97      2.05     125.9      1ASY
ASG  GLN B  383  316    T          Turn   -140.36    -21.78      14.4      1ASY
ASG  TYR B  384  317    T          Turn   -132.86     62.85      34.2      1ASY
ASG  PRO B  385  318    T          Turn    -56.17    117.82      91.3      1ASY
ASG  VAL B  386  319    C          Coil   -141.14    155.32      23.3      1ASY
ASG  GLU B  387  320    C          Coil    -67.83    152.98     125.9      1ASY
ASG  GLU B  388  321    C          Coil    -64.36    130.49     139.6      1ASY
ASG  PHE B  389  322    C          Coil    -53.12    133.70      19.3      1ASY
ASG  LYS B  390  323    C          Coil   -113.99    154.98      52.3      1ASY
ASG  LEU B  391  324    C          Coil   -160.61    148.41      53.4      1ASY
ASG  PRO B  392  325    T          Turn    -35.43    125.23       4.6      1ASY
ASG  LYS B  393  326    T          Turn    -51.75    -39.52     149.5      1ASY
ASG  ASP B  394  327    T          Turn    -80.18      6.71      97.4      1ASY
ASG  GLY B  395  328    T          Turn     76.40    -51.28      30.1      1ASY
ASG  LYS B  396  329    C          Coil    -35.31    110.97     151.5      1ASY
ASG  MET B  397  330    C          Coil    -64.40    150.80      25.6      1ASY
ASG  VAL B  398  331    E        Strand    -90.84    118.62      16.4      1ASY
ASG  ARG B  399  332    E        Strand   -125.74    134.27      95.2      1ASY
ASG  LEU B  400  333    E        Strand   -158.25    130.56       7.1      1ASY
ASG  THR B  401  334    C          Coil    -52.92    153.25      44.3      1ASY
ASG  TYR B  402  335    H    AlphaHelix    -59.40    -27.16       1.2      1ASY
ASG  LYS B  403  336    H    AlphaHelix    -60.12    -58.54     119.5      1ASY
ASG  GLU B  404  337    H    AlphaHelix    -58.94    -33.38      72.6      1ASY
ASG  GLY B  405  338    H    AlphaHelix    -55.26    -38.38       1.0      1ASY
ASG  ILE B  406  339    H    AlphaHelix    -82.01    -37.29       2.4      1ASY
ASG  GLU B  407  340    H    AlphaHelix    -53.18    -46.51     124.6      1ASY
ASG  MET B  408  341    H    AlphaHelix    -60.73    -54.78      32.3      1ASY
ASG  LEU B  409  342    H    AlphaHelix    -54.83    -49.04       0.0      1ASY
ASG  ARG B  410  343    H    AlphaHelix    -65.46    -44.18     100.8      1ASY
ASG  ALA B  411  344    H    AlphaHelix    -67.25      3.92      89.2      1ASY
ASG  ALA B  412  345    C          Coil   -128.74     29.29      48.8      1ASY
ASG  GLY B  413  346    C          Coil     80.63     -7.25      59.3      1ASY
ASG  LYS B  414  347    C          Coil    -70.45    143.71      65.5      1ASY
ASG  GLU B  415  348    C          Coil   -113.81     91.92     181.4      1ASY
ASG  ILE B  416  349    C          Coil   -125.61    148.05      10.2      1ASY
ASG  GLY B  417  350    T          Turn    -80.95    142.48      29.8      1ASY
ASG  ASP B  418  351    T          Turn    -44.06    -22.13      76.4      1ASY
ASG  PHE B  419  352    T          Turn   -133.71     50.40     101.8      1ASY
ASG  GLU B  420  353    T          Turn   -113.80    138.19      96.2      1ASY
ASG  ASP B  421  354    C          Coil    -67.67    117.41     103.3      1ASY
ASG  LEU B  422  355    C          Coil    -51.29    137.39      13.0      1ASY
ASG  SER B  423  356    C          Coil    -93.84    167.84      31.8      1ASY
ASG  THR B  424  357    H    AlphaHelix    -49.03    -49.73      52.0      1ASY
ASG  GLU B  425  358    H    AlphaHelix    -61.41    -45.74     117.3      1ASY
ASG  ASN B  426  359    H    AlphaHelix    -69.63    -31.25      24.3      1ASY
ASG  GLU B  427  360    H    AlphaHelix    -60.91    -60.68      22.2      1ASY
ASG  LYS B  428  361    H    AlphaHelix    -53.99    -47.04      80.6      1ASY
ASG  PHE B  429  362    H    AlphaHelix    -58.23    -48.30      49.5      1ASY
ASG  LEU B  430  363    H    AlphaHelix    -61.77    -36.08       0.0      1ASY
ASG  GLY B  431  364    H    AlphaHelix    -57.34    -53.94       8.3      1ASY
ASG  LYS B  432  365    H    AlphaHelix    -51.99    -48.00     118.7      1ASY
ASG  LEU B  433  366    H    AlphaHelix    -55.76    -48.99      38.9      1ASY
ASG  VAL B  434  367    H    AlphaHelix    -63.97    -37.29       0.6      1ASY
ASG  ARG B  435  368    H    AlphaHelix    -51.67    -43.82      59.9      1ASY
ASG  ASP B  436  369    H    AlphaHelix    -80.75    -58.51     118.0      1ASY
ASG  LYS B  437  370    H    AlphaHelix    -47.00    -48.77     129.5      1ASY
ASG  TYR B  438  371    H    AlphaHelix   -115.82     -9.19      69.4      1ASY
ASG  ASP B  439  372    C          Coil     66.51     52.76      74.1      1ASY
ASG  THR B  440  373    T          Turn   -148.16    133.29       3.1      1ASY
ASG  ASP B  441  374    T          Turn    -84.74      5.45      10.4      1ASY
ASG  PHE B  442  375    E        Strand   -148.56    130.54       0.0      1ASY
ASG  TYR B  443  376    E        Strand   -148.77    163.10       3.8      1ASY
ASG  ILE B  444  377    E        Strand   -110.43    121.25       0.0      1ASY
ASG  LEU B  445  378    E        Strand    -99.70     99.97       0.2      1ASY
ASG  ASP B  446  379    T          Turn    -62.90   -139.84       5.6      1ASY
ASG  LYS B  447  380    T          Turn    -30.62     64.96      30.9      1ASY
ASG  PHE B  448  381    T          Turn    -54.24    159.20       8.8      1ASY
ASG  PRO B  449  382    T          Turn    -74.77    145.04       1.0      1ASY
ASG  LEU B  450  383    T          Turn    -60.57    -43.28       7.2      1ASY
ASG  GLU B  451  384    T          Turn    -53.89    -28.48     147.5      1ASY
ASG  ILE B  452  385    T          Turn    -83.16    -39.35      58.0      1ASY
ASG  ARG B  453  386    T          Turn    -65.77    154.12      25.4      1ASY
ASG  PRO B  454  387    T          Turn    -69.33    154.15      42.0      1ASY
ASG  PHE B  455  388    T          Turn    -31.94    -47.82       3.4      1ASY
ASG  TYR B  456  389    T          Turn    -75.99     12.12      40.3      1ASY
ASG  THR B  457  390    B        Bridge    -92.39    139.53       1.2      1ASY
ASG  MET B  458  391    C          Coil    -73.66    123.55       0.4      1ASY
ASG  PRO B  459  392    E        Strand    -61.93    153.32      15.0      1ASY
ASG  ASP B  460  393    E        Strand    -77.05    138.79      21.6      1ASY
ASG  PRO B  461  394    T          Turn    -60.68    -23.21      22.0      1ASY
ASG  ALA B  462  395    T          Turn   -127.46     60.45      72.7      1ASY
ASG  ASN B  463  396    E        Strand    140.93     82.32      66.1      1ASY
ASG  PRO B  464  397    E        Strand    -58.53      9.87      88.3      1ASY
ASG  LYS B  465  398    E        Strand    -96.60    -31.45     118.1      1ASY
ASG  TYR B  466  399    E        Strand    -92.61   -167.77      38.3      1ASY
ASG  SER B  467  400    E        Strand   -165.74    154.46       0.0      1ASY
ASG  ASN B  468  401    T          Turn    -79.54     83.11       0.0      1ASY
ASG  SER B  469  402    E        Strand   -137.13    170.55       0.0      1ASY
ASG  TYR B  470  403    E        Strand   -170.00    156.91       0.0      1ASY
ASG  ASP B  471  404    E        Strand   -137.05    156.91       3.4      1ASY
ASG  PHE B  472  405    E        Strand   -117.27    134.52       0.0      1ASY
ASG  PHE B  473  406    E        Strand   -122.21    135.90       3.6      1ASY
ASG  MET B  474  407    E        Strand   -128.73    123.81       0.0      1ASY
ASG  ARG B  475  408    T          Turn     53.93     46.83      40.6      1ASY
ASG  GLY B  476  409    T          Turn     67.53     -5.60       9.1      1ASY
ASG  GLU B  477  410    E        Strand   -107.37    165.37      17.0      1ASY
ASG  GLU B  478  411    E        Strand    -89.52    128.49      56.7      1ASY
ASG  ILE B  479  412    E        Strand   -110.44    -47.06      10.0      1ASY
ASG  LEU B  480  413    E        Strand   -115.71    163.03       0.8      1ASY
ASG  SER B  481  414    E        Strand   -157.15    101.91      47.7      1ASY
ASG  GLY B  482  415    E        Strand   -128.54    169.74       3.7      1ASY
ASG  ALA B  483  416    E        Strand   -171.91    159.44       9.2      1ASY
ASG  GLN B  484  417    E        Strand    -70.81    137.54       0.0      1ASY
ASG  ARG B  485  418    E        Strand    -99.11    157.54       9.4      1ASY
ASG  ILE B  486  419    C          Coil    -82.11    103.58       0.2      1ASY
ASG  HIS B  487  420    C          Coil    -79.51    -38.70       9.0      1ASY
ASG  ASP B  488  421    C          Coil    -54.10    135.81      56.0      1ASY
ASG  HIS B  489  422    H    AlphaHelix    -73.70    -36.25      49.1      1ASY
ASG  ALA B  490  423    H    AlphaHelix    -67.94    -61.96      61.8      1ASY
ASG  LEU B  491  424    H    AlphaHelix    -48.10    -49.21      28.2      1ASY
ASG  LEU B  492  425    H    AlphaHelix    -58.24    -24.90       0.0      1ASY
ASG  GLN B  493  426    H    AlphaHelix    -79.53    -25.28      68.7      1ASY
ASG  GLU B  494  427    H    AlphaHelix    -68.00    -69.94     134.3      1ASY
ASG  ARG B  495  428    H    AlphaHelix    -47.81    -27.50      46.1      1ASY
ASG  MET B  496  429    H    AlphaHelix    -66.23    -57.23       0.0      1ASY
ASG  LYS B  497  430    H    AlphaHelix    -58.80    -36.96     144.8      1ASY
ASG  ALA B  498  431    H    AlphaHelix    -55.37    -47.29      65.9      1ASY
ASG  HIS B  499  432    H    AlphaHelix    -81.25     12.85      61.3      1ASY
ASG  GLY B  500  433    C          Coil     74.83     30.08      68.9      1ASY
ASG  LEU B  501  434    C          Coil   -104.80    147.91      22.5      1ASY
ASG  SER B  502  435    T          Turn   -104.26    107.30      56.8      1ASY
ASG  PRO B  503  436    T          Turn    -54.78    -33.06      17.0      1ASY
ASG  GLU B  504  437    T          Turn    -74.99     10.12     138.2      1ASY
ASG  ASP B  505  438    T          Turn    -92.56    153.42      37.4      1ASY
ASG  PRO B  506  439    G      310Helix    -45.32    -59.45      88.2      1ASY
ASG  GLY B  507  440    G      310Helix    -53.34    -30.63      14.7      1ASY
ASG  LEU B  508  441    G      310Helix   -105.76    -10.68       0.2      1ASY
ASG  LYS B  509  442    H    AlphaHelix    -47.42    -81.42      54.9      1ASY
ASG  ASP B  510  443    H    AlphaHelix    -49.11    -46.93      46.4      1ASY
ASG  TYR B  511  444    H    AlphaHelix    -53.96    -44.12       9.0      1ASY
ASG  CYS B  512  445    H    AlphaHelix    -68.54    -57.06       2.2      1ASY
ASG  ASP B  513  446    H    AlphaHelix    -44.39    -41.42      51.9      1ASY
ASG  GLY B  514  447    H    AlphaHelix    -50.86    -27.39       0.6      1ASY
ASG  PHE B  515  448    H    AlphaHelix    -84.68    -19.69       6.4      1ASY
ASG  SER B  516  449    H    AlphaHelix    -65.37    -29.82      29.6      1ASY
ASG  TYR B  517  450    H    AlphaHelix    -74.70     10.94      30.5      1ASY
ASG  GLY B  518  451    C          Coil     92.76    140.86       0.0      1ASY
ASG  CYS B  519  452    C          Coil   -173.01    136.46       1.2      1ASY
ASG  PRO B  520  453    C          Coil    -81.27    174.89       0.4      1ASY
ASG  PRO B  521  454    C          Coil    -75.95    143.41       0.2      1ASY
ASG  HIS B  522  455    E        Strand   -155.93    119.15       0.0      1ASY
ASG  ALA B  523  456    E        Strand    -98.15    152.20       0.0      1ASY
ASG  GLY B  524  457    E        Strand   -151.56   -134.73       0.0      1ASY
ASG  GLY B  525  458    E        Strand    138.07    132.70       0.0      1ASY
ASG  GLY B  526  459    E        Strand    -86.39   -178.81      17.8      1ASY
ASG  ILE B  527  460    E        Strand   -158.55    164.17      12.3      1ASY
ASG  GLY B  528  461    B        Bridge   -127.24    120.21       4.6      1ASY
ASG  LEU B  529  462    H    AlphaHelix    -51.48    -57.57       0.0      1ASY
ASG  GLU B  530  463    H    AlphaHelix    -52.49    -58.46       8.6      1ASY
ASG  ARG B  531  464    H    AlphaHelix    -53.05    -35.62      39.3      1ASY
ASG  VAL B  532  465    H    AlphaHelix    -64.70    -40.60       2.8      1ASY
ASG  VAL B  533  466    H    AlphaHelix    -71.46    -52.35       1.0      1ASY
ASG  MET B  534  467    H    AlphaHelix    -43.73    -62.33       0.6      1ASY
ASG  PHE B  535  468    H    AlphaHelix    -66.91    -16.01       5.8      1ASY
ASG  TYR B  536  469    H    AlphaHelix    -80.16    -56.09      25.2      1ASY
ASG  LEU B  537  470    H    AlphaHelix    -80.10    -10.00       1.7      1ASY
ASG  ASP B  538  471    C          Coil     64.96     26.85      33.1      1ASY
ASG  LEU B  539  472    C          Coil    -50.56     -6.21       1.3      1ASY
ASG  LYS B  540  473    C          Coil     57.74     13.66     129.5      1ASY
ASG  ASN B  541  474    C          Coil   -173.37    120.11      27.9      1ASY
ASG  ILE B  542  475    G      310Helix    -48.98    -40.51       5.6      1ASY
ASG  ARG B  543  476    G      310Helix    -52.95    -19.46      24.5      1ASY
ASG  ARG B  544  477    G      310Helix    -75.00    -38.50      41.5      1ASY
ASG  ALA B  545  478    C          Coil    -90.37     34.57       0.0      1ASY
ASG  SER B  546  479    T          Turn   -158.83    121.53       9.7      1ASY
ASG  LEU B  547  480    T          Turn    -44.76    -32.50       3.4      1ASY
ASG  PHE B  548  481    T          Turn   -154.24     48.82       6.9      1ASY
ASG  PRO B  549  482    T          Turn    -31.63    150.82       6.5      1ASY
ASG  ARG B  550  483    C          Coil   -135.85    143.71       4.1      1ASY
ASG  ASP B  551  484    B        Bridge   -145.90    173.61      16.2      1ASY
ASG  PRO B  552  485    T          Turn    -48.67    -22.46      18.5      1ASY
ASG  LYS B  553  486    T          Turn   -108.30    -22.18     152.4      1ASY
ASG  ARG B  554  487    B        Bridge   -103.72    107.85      35.1      1ASY
ASG  LEU B  555  488    C          Coil   -132.54     42.32      25.5      1ASY
ASG  ARG B  556  489    C          Coil   -178.61    135.93      93.3      1ASY
ASG  PRO B  557  490    C          Coil    -86.55    360.00      36.7      1ASY

